/** Additional purpose-built packs for categories that had fewer than five choices. */
import type { PackField, PackSpec } from './generate.js';

const f = {
  text: (key: string, label: string, required = true): PackField => ({ key, label, type: 'short_text', required, classification: 'internal' }),
  person: (key: string, label: string, required = true): PackField => ({ key, label, type: 'short_text', required, classification: 'confidential' }),
  email: (key: string, label: string, required = true): PackField => ({ key, label, type: 'email', required, classification: 'confidential' }),
  phone: (key: string, label: string, required = false): PackField => ({ key, label, type: 'phone', required, classification: 'confidential' }),
  notes: (key: string, label: string, required = true): PackField => ({ key, label, type: 'long_text', required, classification: 'confidential' }),
  date: (key: string, label: string, required = true): PackField => ({ key, label, type: 'date', required, classification: 'internal' }),
  money: (key: string, label: string, required = true): PackField => ({ key, label, type: 'currency', required, classification: 'confidential' }),
  choice: (key: string, label: string, choices: string[], required = true): PackField => ({ key, label, type: 'dropdown', choices, required, classification: 'internal' }),
  yesNo: (key: string, label: string, required = true): PackField => ({ key, label, type: 'yes_no', required, classification: 'internal' }),
  private: (key: string, label: string, reason: string, required = false): PackField => ({ key, label, type: 'long_text', required, classification: 'restricted', reason }),
  recorded: (key: string, label: string): PackField => ({ key, label, type: 'short_text', required: false, classification: 'internal', setBy: 'operator', help: 'The assigned team records this after completing the work.' }),
};

export const EXTRA_PACKS: PackSpec[] = [
  // Communications
  {
    key: 'content_approval', name: 'Content approval', category: 'Communications',
    summary: 'A public message checked for accuracy, consent and timing before release.',
    audience: 'For teams publishing news, campaigns or social posts.', outcome: 'The approved version is published with a release reference.',
    respondents: 'The person requesting publication.', ownerName: 'Communications',
    approvals: [{ key: 'editor', name: 'Editorial review', byRole: 'comms_lead', dueInHours: 8 }, { key: 'owner', name: 'Subject owner', byRole: 'department_head', dueInHours: 8 }],
    task: { key: 'publish_content', name: 'Publish the approved version', byRole: 'process_owner', description: 'Check the final version, permissions and scheduled channel; publish only the approved copy and record its link.', requiredFields: ['published_link_reference'] },
    completionMessage: 'The approved content has been published and its link recorded.', retentionDays: 1095,
    fields: [f.choice('channel', 'Where will it appear?', ['website', 'email', 'social', 'press']), f.text('headline', 'Headline or working title'), f.notes('message', 'What needs to be said'), f.date('release_date', 'Planned release date'), f.yesNo('people_identifiable', 'Does it identify anyone?'), f.text('approved_copy_reference', 'Copy or file version to review'), f.recorded('published_link_reference', 'Published link or release reference')],
  },
  {
    key: 'crisis_statement', name: 'Urgent statement request', category: 'Communications',
    summary: 'A time-critical public statement checked by the right people before it is issued.',
    audience: 'For teams responding to an incident or breaking story.', outcome: 'An authorised statement is issued or a documented decision is made to withhold it.',
    respondents: 'The incident lead or person requesting a statement.', ownerName: 'Communications',
    approvals: [{ key: 'comms', name: 'Communications check', byRole: 'comms_lead', dueInHours: 4 }, { key: 'authority', name: 'Authorised spokesperson', byRole: 'department_head', dueInHours: 6 }],
    task: { key: 'issue_statement', name: 'Issue or withhold the statement', byRole: 'process_owner', description: 'Verify facts and affected people, release only authorised wording, or document why no statement was issued.', requiredFields: ['statement_decision_reference'] },
    completionMessage: 'The statement decision and release record are filed.', notes: ['This process does not override an incident response or legal notification duty.'], retentionDays: 1825,
    fields: [f.text('incident_reference', 'Incident reference'), f.notes('confirmed_facts', 'Facts confirmed so far'), f.choice('audience', 'Intended audience', ['public', 'staff', 'customers', 'media']), f.date('response_due', 'Response needed by'), f.notes('proposed_words', 'Proposed wording'), f.recorded('statement_decision_reference', 'Statement release or withholding reference')],
  },
  {
    key: 'website_correction', name: 'Website correction', category: 'Communications',
    summary: 'An inaccurate public page corrected with an owner and a record of the change.',
    audience: 'For teams whose website changes need a check.', outcome: 'The corrected page is live and checked.',
    respondents: 'Anyone who spots an issue.', ownerName: 'Communications',
    approvals: [{ key: 'editor', name: 'Editorial review', byRole: 'comms_lead', dueInHours: 8 }],
    task: { key: 'correct_page', name: 'Correct and verify the page', byRole: 'process_owner', description: 'Confirm the correct information with its owner, update the page and check the live result.', requiredFields: ['corrected_page_reference'] },
    completionMessage: 'The corrected page has been checked and recorded.', retentionDays: 1095,
    fields: [f.text('page_url', 'Page URL'), f.choice('problem_kind', 'What is wrong?', ['fact', 'broken_link', 'accessibility', 'outdated', 'other']), f.notes('current_problem', 'What needs correcting'), f.notes('proposed_correction', 'Suggested correction', false), f.choice('urgency', 'How urgent?', ['today', 'this_week', 'routine']), f.recorded('corrected_page_reference', 'Corrected page reference')],
  },

  // Customer
  {
    key: 'return_replacement', name: 'Return or replacement request', category: 'Customer',
    summary: 'A product issue checked against an order and resolved with a recorded return or replacement.',
    audience: 'For a support team handling product returns.', outcome: 'The customer receives a decision and the agreed remedy is recorded.',
    respondents: 'A customer.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Support review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'arrange_remedy', name: 'Arrange the agreed remedy', byRole: 'process_owner', description: 'Check the order, return condition and applicable terms; arrange the approved remedy in the order system and record its reference.', requiredFields: ['remedy_reference'] },
    completionMessage: 'The agreed return or replacement has been arranged.', notes: ['Any refund is performed separately in the payment provider after approval.'], retentionDays: 2190,
    fields: [f.text('order_number', 'Order number'), f.text('item_name', 'Item'), f.date('received_on', 'Date received'), f.choice('issue_kind', 'What is wrong?', ['damaged', 'faulty', 'wrong_item', 'unwanted']), f.notes('issue_detail', 'Describe the issue'), f.choice('preferred_remedy', 'What would you prefer?', ['replacement', 'refund', 'repair']), f.recorded('remedy_reference', 'Return or remedy reference')],
  },
  {
    key: 'delivery_problem', name: 'Delivery problem', category: 'Customer',
    summary: 'A missing, late or damaged delivery investigated and resolved.',
    audience: 'For customer teams tracing shipments.', outcome: 'The delivery issue is investigated and the customer receives the agreed outcome.',
    respondents: 'A customer.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Delivery support review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'trace_delivery', name: 'Trace and resolve delivery', byRole: 'process_owner', description: 'Check tracking and carrier evidence, agree the next action with the customer and record the carrier or replacement reference.', requiredFields: ['delivery_resolution_reference'] },
    completionMessage: 'The delivery issue and agreed next action have been recorded.', retentionDays: 2190,
    fields: [f.text('order_number', 'Order number'), f.text('tracking_number', 'Tracking number', false), f.choice('delivery_issue', 'What happened?', ['late', 'missing', 'damaged', 'wrong_address']), f.date('expected_on', 'Expected delivery date'), f.notes('delivery_detail', 'Tell us what happened'), f.choice('preferred_contact', 'How should we contact you?', ['email', 'phone']), f.recorded('delivery_resolution_reference', 'Delivery resolution reference')],
  },
  {
    key: 'service_change', name: 'Service change request', category: 'Customer',
    summary: 'A customer change to an active service checked for eligibility and carried through.',
    audience: 'For subscription or service support teams.', outcome: 'The requested change is applied or declined with the reason recorded.',
    respondents: 'A customer or account contact.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Service change review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'apply_change', name: 'Apply and confirm the change', byRole: 'process_owner', description: 'Check authority and applicable terms, apply the agreed change in the service system and send confirmation.', requiredFields: ['service_change_reference'] },
    completionMessage: 'Your service change has been applied and recorded.', notes: ['This form does not automatically cancel billing or issue a refund.'], retentionDays: 2190,
    fields: [f.text('account_reference', 'Account or service reference'), f.choice('change_kind', 'Requested change', ['plan', 'address', 'contact', 'pause', 'cancel']), f.date('effective_from', 'When should it start?'), f.notes('change_detail', 'What should change?'), f.yesNo('account_authority', 'Are you authorised to request this?'), f.recorded('service_change_reference', 'Service change reference')],
  },

  // Education
  {
    key: 'assessment_extension', name: 'Assessment extension', category: 'Education',
    summary: 'A deadline change reviewed against course rules and communicated to the learner.',
    audience: 'For schools and training providers managing coursework deadlines.', outcome: 'An extension decision and new deadline are recorded.',
    respondents: 'A learner or parent acting for one.', ownerName: 'Academic office',
    approvals: [{ key: 'tutor', name: 'Course tutor', byRole: 'course_tutor', dueInHours: 48 }],
    task: { key: 'update_deadline', name: 'Update the assessment record', byRole: 'process_owner', description: 'Apply the approved deadline in the learning system, notify the learner and record the change reference.', requiredFields: ['extension_reference'] },
    completionMessage: 'The extension decision and any new deadline have been recorded.', notes: ['Evidence requirements and allowable extensions depend on the provider’s policy.'], retentionDays: 1095,
    fields: [f.text('course_name', 'Course'), f.text('assessment_name', 'Assessment'), f.date('current_deadline', 'Current deadline'), f.date('requested_deadline', 'Requested deadline'), f.notes('extension_reason', 'Why do you need more time?'), f.recorded('extension_reference', 'Extension decision reference')],
  },
  {
    key: 'student_wellbeing', name: 'Student wellbeing concern', category: 'Education',
    summary: 'A concern about a student routed privately for timely human review.',
    audience: 'For staff who need a clear route to the safeguarding team.', outcome: 'The concern is assessed and a safe follow-up is recorded.',
    respondents: 'A staff member or parent.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'safeguarding', name: 'Safeguarding review', byRole: 'safeguarding_lead', dueInHours: 24 }],
    task: { key: 'follow_up', name: 'Record safeguarding follow-up', byRole: 'safeguarding_lead', description: 'Assess immediate risk, use the organisation’s safeguarding route, make necessary referrals outside this form and record a secure case reference.', requiredFields: ['wellbeing_case_reference'] },
    completionMessage: 'The concern has been reviewed and follow-up recorded by the safeguarding team.', notes: ['Immediate danger needs the local emergency route. Do not use routine email to repeat the private concern.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('student_name', 'Student name'), f.text('class_group', 'Class or group', false), f.date('noticed_on', 'When was this noticed?'), f.choice('concern_kind', 'Kind of concern', ['wellbeing', 'attendance', 'safety', 'other']), f.private('concern_detail', 'What have you observed?', 'Student welfare details are restricted to the safeguarding team.', true), f.yesNo('immediate_risk', 'Is someone in immediate danger?'), f.recorded('wellbeing_case_reference', 'Secure case reference')],
  },

  // Facilities
  {
    key: 'building_access', name: 'Building access request', category: 'Facilities',
    summary: 'Physical access granted for a named person, place and period with a return record.',
    audience: 'For facilities teams managing keys or badges.', outcome: 'Access is authorised, issued and tracked for return.',
    respondents: 'A manager or building user.', ownerName: 'Facilities',
    approvals: [{ key: 'facilities', name: 'Facilities approval', byRole: 'facilities_manager', dueInHours: 24 }],
    task: { key: 'issue_access', name: 'Issue and record access', byRole: 'process_owner', description: 'Confirm identity, area and end date; issue the key or badge, record its identifier and arrange its return.', requiredFields: ['access_issue_reference'] },
    completionMessage: 'The authorised building access has been issued and recorded.', retentionDays: 1825,
    fields: [f.person('access_for', 'Who needs access?'), f.choice('access_kind', 'Access type', ['key', 'badge', 'visitor_pass', 'temporary_code']), f.text('area', 'Building or area'), f.date('access_from', 'Start date'), f.date('access_until', 'End date'), f.notes('business_reason', 'Why is access needed?'), f.recorded('access_issue_reference', 'Key or badge issue reference')],
  },

  // Health & safety
  {
    key: 'safety_inspection', name: 'Safety inspection', category: 'Health & safety',
    summary: 'An inspection finding assigned to an owner and closed with evidence.',
    audience: 'For site teams recording routine safety checks.', outcome: 'Findings are made safe, assigned and verified.',
    respondents: 'An inspector or site lead.', ownerName: 'Health and safety',
    approvals: [{ key: 'safety', name: 'Safety lead review', byRole: 'safety_lead', dueInHours: 24 }],
    task: { key: 'close_findings', name: 'Assign and verify findings', byRole: 'safety_lead', description: 'Make urgent hazards safe, assign each finding and due date, verify corrective work and record the inspection log.', requiredFields: ['inspection_log_reference'] },
    completionMessage: 'The inspection findings and corrective actions have been recorded.', retentionDays: 3650,
    fields: [f.date('inspection_date', 'Inspection date'), f.text('site', 'Site or area'), f.choice('inspection_kind', 'Inspection type', ['routine', 'fire', 'equipment', 'contractor']), f.choice('highest_risk', 'Highest risk found', ['none', 'low', 'medium', 'high']), f.notes('findings', 'Findings and evidence'), f.yesNo('area_made_safe', 'Was any urgent hazard made safe?'), f.recorded('inspection_log_reference', 'Inspection log reference')],
  },

  // Healthcare: these request human clinical review; they never prescribe or diagnose.
  {
    key: 'prescription_renewal', name: 'Prescription renewal request', category: 'Healthcare',
    summary: 'A medication renewal request checked by a clinician before a prescription is issued.',
    audience: 'For a clinical team receiving repeat-medication requests.', outcome: 'A clinician decides and records the prescription or follow-up outcome.',
    respondents: 'A patient or authorised carer.', ownerName: 'Clinical administration',
    approvals: [{ key: 'clinician', name: 'Clinician review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'record_renewal', name: 'Record the clinical outcome', byRole: 'clinician', description: 'Check the clinical record, safety and eligibility; prescribe only through the clinical system or arrange a review, then record its reference.', requiredFields: ['renewal_outcome_reference'] },
    completionMessage: 'A clinician has reviewed the request and recorded the next step.', notes: ['Submitting this form is not a prescription. Urgent symptoms need the local urgent-care route.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.text('patient_reference', 'Patient record reference'), f.person('patient_name', 'Patient name'), f.private('medicine_requested', 'Medicine and dose requested', 'Medication information is clinical data for the reviewing clinician.', true), f.date('supply_runs_out', 'When will your supply run out?'), f.private('recent_changes', 'Any recent changes or concerns?', 'Treatment concerns must be reviewed privately by a clinician.'), f.recorded('renewal_outcome_reference', 'Clinical renewal outcome reference')],
  },
  {
    key: 'test_result_enquiry', name: 'Test result enquiry', category: 'Healthcare',
    summary: 'A test result query routed for identity checking and clinical interpretation.',
    audience: 'For clinics receiving patient result enquiries.', outcome: 'An authorised clinician gives the result or arranges follow-up through a safe channel.',
    respondents: 'A patient or authorised representative.', ownerName: 'Clinical administration',
    approvals: [{ key: 'clinician', name: 'Clinician review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'respond_result', name: 'Provide result or arrange follow-up', byRole: 'clinician', description: 'Verify identity and authorisation in the clinical record. Call the supplied number through the approved clinical process, interpret the result or arrange follow-up, and record the contact reference. Do not put the result in PatForm or a routine email.', requiredFields: ['result_contact_reference'] },
    completionMessage: 'The clinical team has recorded how your result enquiry was handled.', notes: ['The phone number is for arranging a safe call; staff must verify identity before discussing results. Do not put test results in routine notification emails. This form does not display or diagnose a result.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.text('patient_reference', 'Patient record reference'), f.person('patient_name', 'Patient name'), f.choice('test_kind', 'Type of test', ['blood', 'imaging', 'screening', 'other']), f.date('test_on', 'Date of test'), f.private('enquiry_detail', 'What would you like to ask?', 'A result enquiry may reveal sensitive clinical circumstances.'), f.phone('safe_phone', 'Phone number for a safe call', true), f.recorded('result_contact_reference', 'Result response reference')],
  },
  {
    key: 'care_plan_change', name: 'Care plan change request', category: 'Healthcare',
    summary: 'A proposed care-plan change reviewed clinically and recorded against the right version.',
    audience: 'For care teams coordinating changes without losing the decision trail.', outcome: 'A clinician approves or declines the change and the care plan version is updated.',
    respondents: 'A patient, carer or care-team member.', ownerName: 'Care coordination',
    approvals: [{ key: 'clinical', name: 'Clinical review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'update_plan', name: 'Update and communicate the care plan', byRole: 'clinician', description: 'Check consent, assess the proposed change, update the approved care plan in the clinical system and notify the relevant care team.', requiredFields: ['care_plan_version_reference'] },
    completionMessage: 'The care-plan decision and updated version have been recorded.', notes: ['A change is not effective until the clinical team confirms it in the care record.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.text('patient_reference', 'Patient record reference'), f.text('current_plan_version', 'Current plan version'), f.choice('requested_change', 'What needs changing?', ['medication', 'appointments', 'support', 'goals', 'other']), f.private('change_reason', 'Why is a change needed?', 'The reason may contain private health information.', true), f.date('needed_from', 'Requested start date'), f.yesNo('patient_involved', 'Has the patient been involved in this request?'), f.recorded('care_plan_version_reference', 'Updated care plan version')],
  },

  // Legal
  {
    key: 'nda_request', name: 'Non-disclosure agreement request', category: 'Legal',
    summary: 'A confidentiality agreement checked for parties, purpose and approved wording before signature.',
    audience: 'For teams sharing confidential material with an outside party.', outcome: 'The approved NDA is signed outside this process and filed by version.',
    respondents: 'The relationship owner.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal review', byRole: 'legal_reviewer', dueInHours: 120 }, { key: 'signatory', name: 'Authorised signatory', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'file_nda', name: 'Verify signature and file NDA', byRole: 'process_owner', description: 'Check the executed agreement matches the approved version, file it and record the document reference.', requiredFields: ['signed_nda_reference'] },
    completionMessage: 'The signed NDA has been checked and filed.', notes: ['PatForm records the approval and filing reference; the agreement is signed separately.'], retentionDays: 3650,
    fields: [f.text('counterparty', 'Other party'), f.choice('nda_kind', 'Who discloses?', ['mutual', 'us_only', 'other_party_only']), f.notes('sharing_purpose', 'Purpose of sharing'), f.date('needed_by', 'Needed by'), f.text('draft_version', 'Draft document version'), f.choice('information_kind', 'Information involved', ['commercial', 'technical', 'personal_data', 'other']), f.recorded('signed_nda_reference', 'Signed NDA reference')],
  },
  {
    key: 'legal_hold', name: 'Legal hold request', category: 'Legal',
    summary: 'A preservation request scoped and issued before records are altered or deleted.',
    audience: 'For legal teams handling disputes or investigations.', outcome: 'Relevant custodians are notified and preservation is documented.',
    respondents: 'Legal or an authorised case lead.', ownerName: 'Legal',
    approvals: [{ key: 'counsel', name: 'Counsel review', byRole: 'legal_reviewer', dueInHours: 120 }],
    task: { key: 'issue_hold', name: 'Issue and record the hold', byRole: 'process_owner', description: 'Define custodians, systems, date range and review date; issue the hold through the approved records process and record acknowledgements.', requiredFields: ['hold_notice_reference'] },
    completionMessage: 'The preservation notice and scope have been recorded.', notes: ['Do not use this form as the preservation mechanism itself; retention and deletion systems must be updated separately.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.text('matter_reference', 'Matter reference'), f.date('triggered_on', 'When was the need identified?'), f.private('matter_summary', 'Why is preservation needed?', 'Legal dispute details are privileged or otherwise sensitive.', true), f.notes('systems_in_scope', 'Systems and records in scope'), f.notes('custodian_roles', 'Custodian roles or teams'), f.date('review_on', 'Review date'), f.recorded('hold_notice_reference', 'Hold notice reference')],
  },
  {
    key: 'dispute_intake', name: 'Dispute or claim intake', category: 'Legal',
    summary: 'A legal claim or threatened dispute sent to counsel with dates and documents tracked.',
    audience: 'For teams who receive formal complaints or legal letters.', outcome: 'Counsel has triaged the matter and recorded its response owner and deadline.',
    respondents: 'Whoever received the claim.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal triage', byRole: 'legal_reviewer', dueInHours: 120 }],
    task: { key: 'open_matter', name: 'Open and assign the legal matter', byRole: 'process_owner', description: 'Verify the response deadline, preserve relevant material, assign counsel and record the matter reference.', requiredFields: ['legal_matter_reference'] },
    completionMessage: 'The claim has been triaged and assigned to legal counsel.', notes: ['A filed claim or imminent deadline requires immediate direct notice to counsel; this form alone does not protect a deadline.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.date('received_on', 'Date received'), f.text('claimant', 'Claimant or representative'), f.choice('claim_kind', 'Type of dispute', ['contract', 'employment', 'property', 'injury', 'other']), f.date('response_due', 'Stated response deadline'), f.private('claim_summary', 'What is alleged?', 'Allegations and legal strategy must stay with the legal team.', true), f.text('document_reference', 'Letter or document reference'), f.recorded('legal_matter_reference', 'Legal matter reference')],
  },
  {
    key: 'policy_legal_review', name: 'Policy legal review', category: 'Legal',
    summary: 'A proposed policy checked for legal obligations and approved wording before adoption.',
    audience: 'For teams updating internal policies.', outcome: 'The approved policy version and publication decision are recorded.',
    respondents: 'A policy owner.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal review', byRole: 'legal_reviewer', dueInHours: 120 }, { key: 'owner', name: 'Policy owner approval', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'publish_policy', name: 'Publish the approved version', byRole: 'process_owner', description: 'Check the final text, effective date and staff notice, then publish the approved version and record its reference.', requiredFields: ['policy_version_reference'] },
    completionMessage: 'The approved policy version has been recorded and issued.', retentionDays: 3650,
    fields: [f.text('policy_name', 'Policy name'), f.text('current_version', 'Current version'), f.notes('proposed_change', 'What should change?'), f.notes('reason', 'Why is the change needed?'), f.date('effective_on', 'Proposed effective date'), f.choice('affected_group', 'Who is affected?', ['staff', 'customers', 'suppliers', 'public']), f.recorded('policy_version_reference', 'Published policy version')],
  },

  // Procurement
  {
    key: 'supplier_change', name: 'Supplier details change', category: 'Procurement',
    summary: 'A supplier update verified independently before a vendor record changes.',
    audience: 'For teams guarding against invoice and bank-change fraud.', outcome: 'The supplier change is verified and the vendor record updated.',
    respondents: 'The internal supplier owner.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'finance', name: 'Finance verification', byRole: 'finance_reviewer', dueInHours: 120 }],
    task: { key: 'apply_vendor_change', name: 'Verify and update supplier record', byRole: 'process_owner', description: 'Verify any payment-detail change through a known independent contact, record the verification and update the vendor master.', requiredFields: ['vendor_change_reference'] },
    completionMessage: 'The verified supplier change has been recorded.', notes: ['Do not enter bank account details in this form. Verification must use a separately known contact route.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.text('vendor_reference', 'Existing vendor reference'), f.text('supplier_name', 'Supplier name'), f.choice('change_kind', 'What is changing?', ['contact', 'address', 'tax_details', 'payment_details']), f.notes('requested_change', 'Describe the change without bank numbers'), f.date('requested_on', 'Date requested'), { ...f.text('verification_reference', 'Independent verification reference', false), classification: 'restricted', reason: 'Evidence of payment-detail verification is limited to procurement and finance.' }, f.recorded('vendor_change_reference', 'Updated vendor record reference')],
  },
  {
    key: 'purchase_order_change', name: 'Purchase order change', category: 'Procurement',
    summary: 'A price, quantity or delivery change approved before an order is amended.',
    audience: 'For teams managing changes to placed purchase orders.', outcome: 'The approved change is reflected in the purchase order and supplier notice.',
    respondents: 'The requisitioner or buyer.', ownerName: 'Procurement',
    approvals: [{ key: 'buyer', name: 'Buyer review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'budget', name: 'Budget owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'amend_order', name: 'Amend and reissue the order', byRole: 'process_owner', description: 'Check the current commitment, amend only the approved lines, send the revision to the supplier and record the new order version.', requiredFields: ['amended_po_reference'] },
    completionMessage: 'The amended purchase order has been issued and recorded.', retentionDays: 2555,
    fields: [f.text('po_number', 'Purchase order number'), f.text('supplier_name', 'Supplier'), f.choice('change_kind', 'Change needed', ['quantity', 'price', 'delivery', 'scope', 'cancel_line']), f.notes('old_and_new', 'Current and proposed terms'), f.money('revised_total', 'Revised order total'), f.date('needed_by', 'When is the change needed?'), f.recorded('amended_po_reference', 'Amended PO version')],
  },
  {
    key: 'bid_evaluation', name: 'Bid evaluation', category: 'Procurement',
    summary: 'Supplier offers compared against agreed criteria with conflicts and the award recorded.',
    audience: 'For buyers running a competitive quotation or tender.', outcome: 'An award recommendation is reviewed and the decision documented.',
    respondents: 'The buyer running the comparison.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'budget', name: 'Budget owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'record_award', name: 'Notify bidders and file evaluation', byRole: 'process_owner', description: 'File the evaluation and conflict declarations, notify bidders through the approved route and record the award reference.', requiredFields: ['award_decision_reference'] },
    completionMessage: 'The supplier award decision and evaluation have been recorded.', notes: ['Use your organisation’s procurement thresholds, scoring method and conflict policy.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.text('sourcing_reference', 'Sourcing reference'), f.text('requirement', 'What is being bought?'), f.money('estimated_value', 'Estimated value'), f.text('bids_received', 'Bid references received'), f.notes('criteria_result', 'Evaluation against agreed criteria'), f.yesNo('conflict_declared', 'Has any evaluator declared a conflict?'), f.private('conflict_detail', 'Conflict handling detail', 'Evaluator conflicts require restricted review.'), f.recorded('award_decision_reference', 'Award decision reference')],
  },
  {
    key: 'contract_renewal', name: 'Supplier contract renewal', category: 'Procurement',
    summary: 'A renewal reviewed before notice deadlines and spending commitments take effect.',
    audience: 'For teams tracking recurring supplier contracts.', outcome: 'The contract is renewed, renegotiated or ended with the action recorded.',
    respondents: 'The contract owner.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'owner', name: 'Service owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'execute_renewal', name: 'Carry out the renewal decision', byRole: 'process_owner', description: 'Check notice terms and approved value, send the renewal or termination notice outside PatForm and file the resulting document.', requiredFields: ['renewal_action_reference'] },
    completionMessage: 'The contract renewal decision and action have been recorded.', notes: ['The contract’s actual notice date must be checked against the signed terms; this form does not send legal notice.'], retentionDays: 2555,
    fields: [f.text('supplier_name', 'Supplier'), f.text('contract_reference', 'Contract reference'), f.date('expires_on', 'Contract expiry'), f.date('notice_by', 'Notice deadline'), f.choice('proposed_action', 'Proposed action', ['renew', 'renegotiate', 'retender', 'end']), f.money('renewal_value', 'Proposed renewal value'), f.notes('performance_review', 'Performance and alternatives'), f.recorded('renewal_action_reference', 'Renewal or termination action reference')],
  },

  // Property
  {
    key: 'move_in_inspection', name: 'Move-in inspection', category: 'Property',
    summary: 'A property condition check agreed and filed before occupancy begins.',
    audience: 'For property teams recording condition and handover.', outcome: 'The condition record and keys are documented for the tenancy.',
    respondents: 'A property manager or incoming occupier.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager review', byRole: 'property_manager', dueInHours: 48 }],
    task: { key: 'file_condition', name: 'File inventory and handover', byRole: 'process_owner', description: 'Check the signed condition record and meter readings, agree any defects and record the handover reference.', requiredFields: ['move_in_record_reference'] },
    completionMessage: 'The move-in condition and handover record have been filed.', retentionDays: 2555,
    fields: [f.text('property_reference', 'Property reference'), f.date('inspection_on', 'Inspection date'), f.date('tenancy_starts', 'Tenancy start date'), f.notes('condition_summary', 'Condition and defects'), f.text('meter_readings', 'Meter readings', false), f.yesNo('keys_received', 'Were keys received?'), f.text('inventory_document_reference', 'Inventory document reference'), f.recorded('move_in_record_reference', 'Move-in record reference')],
  },
  {
    key: 'deposit_return', name: 'Deposit return review', category: 'Property',
    summary: 'Proposed deposit deductions checked against evidence before a return is processed.',
    audience: 'For property teams closing a tenancy.', outcome: 'A supported deposit decision is communicated and its payment reference recorded.',
    respondents: 'A property manager or tenancy administrator.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager', byRole: 'property_manager', dueInHours: 48 }, { key: 'finance', name: 'Finance check', byRole: 'finance_reviewer', dueInHours: 72 }],
    task: { key: 'process_deposit', name: 'Record the deposit outcome', byRole: 'process_owner', description: 'Check the inventory and local deposit rules, communicate proposed deductions and process any return in the deposit scheme or payment provider.', requiredFields: ['deposit_outcome_reference'] },
    completionMessage: 'The deposit outcome has been recorded and communicated.', notes: ['Deposit deadlines and dispute rights vary by place and scheme; verify them before use.'], retentionDays: 2555,
    fields: [f.text('tenancy_reference', 'Tenancy reference'), f.date('vacated_on', 'Date vacated'), f.money('deposit_held', 'Deposit held'), f.money('proposed_deductions', 'Proposed deductions', false), f.notes('deduction_evidence', 'Condition evidence and reasons', false), f.text('scheme_reference', 'Deposit scheme reference', false), f.recorded('deposit_outcome_reference', 'Deposit outcome reference')],
  },
  {
    key: 'lease_renewal', name: 'Lease renewal enquiry', category: 'Property',
    summary: 'A renewal request checked against the current agreement and answered before expiry.',
    audience: 'For landlords and property managers handling occupier renewals.', outcome: 'The renewal decision and next contract step are recorded.',
    respondents: 'A tenant or property manager.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager review', byRole: 'property_manager', dueInHours: 48 }],
    task: { key: 'arrange_renewal', name: 'Arrange the agreed renewal', byRole: 'process_owner', description: 'Check the existing terms and any applicable notices, agree the proposed dates and issue documents through the usual legal route.', requiredFields: ['renewal_document_reference'] },
    completionMessage: 'The lease renewal decision and document step have been recorded.', notes: ['This is an enquiry and approval trail, not a signed lease or formal notice.'], retentionDays: 2555,
    fields: [f.text('property_reference', 'Property reference'), f.text('tenancy_reference', 'Current agreement reference'), f.date('current_end', 'Current end date'), f.date('preferred_end', 'Preferred new end date'), f.choice('request_kind', 'What is requested?', ['renew_same_terms', 'change_terms', 'end_at_expiry']), f.notes('requested_changes', 'Changes requested', false), f.recorded('renewal_document_reference', 'Renewal document reference')],
  },

  // Safeguarding
  {
    key: 'safeguarding_concern', name: 'Safeguarding concern', category: 'Safeguarding',
    summary: 'A concern about someone’s safety sent privately to the safeguarding lead for prompt action.',
    audience: 'For churches, schools and charities receiving welfare concerns.', outcome: 'A trained lead assesses the concern and records a secure case reference.',
    respondents: 'A staff member, volunteer or person raising a concern.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Safeguarding lead review', byRole: 'safeguarding_lead', dueInHours: 4 }],
    task: { key: 'record_action', name: 'Record the safeguarding action', byRole: 'safeguarding_lead', description: 'Assess immediate safety, follow the local safeguarding procedure, make any necessary referral and record the secure case reference.', requiredFields: ['safeguarding_case_reference'] },
    completionMessage: 'The safeguarding team has reviewed the concern.', notes: ['If anyone is in immediate danger, use the emergency route instead of waiting for this form.', 'Do not include the private concern in routine email notifications.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('person_at_risk', 'Person the concern is about'), f.date('noticed_on', 'When did this happen or become known?'), f.choice('concern_type', 'What kind of concern?', ['safety', 'conduct', 'neglect', 'disclosure', 'other']), f.private('concern_detail', 'What happened? Record facts and exact words where possible.', 'Safeguarding details are restricted to the safeguarding team.', true), f.yesNo('immediate_danger', 'Is someone in immediate danger now?'), f.text('others_informed', 'Who has already been told?', false), f.recorded('safeguarding_case_reference', 'Secure case reference')],
  },
  {
    key: 'safeguarding_allegation', name: 'Allegation against a worker', category: 'Safeguarding',
    summary: 'An allegation about a worker routed confidentially to an independent safeguarding decision maker.',
    audience: 'For organisations that need a separate route for concerns about staff or volunteers.', outcome: 'The allegation is triaged and referred through the organisation’s formal procedure.',
    respondents: 'The person reporting the allegation.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'designated_lead', name: 'Designated safeguarding review', byRole: 'safeguarding_lead', dueInHours: 4 }],
    task: { key: 'allegation_route', name: 'Record referral and protective steps', byRole: 'safeguarding_lead', description: 'Keep the allegation away from the person named; follow the required external and internal referral route and record a secure reference.', requiredFields: ['allegation_case_reference'] },
    completionMessage: 'The designated safeguarding lead has reviewed the report.', notes: ['Do not investigate or notify the person named through an automatic message.', 'Use the emergency route for immediate danger.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('worker_name', 'Worker named in the allegation'), f.text('worker_role', 'Their role', false), f.date('incident_date', 'When did this happen or become known?'), f.private('allegation_detail', 'Describe what was reported', 'Allegations are restricted to the designated safeguarding team.', true), f.yesNo('immediate_danger', 'Is someone in immediate danger now?'), f.text('existing_reference', 'Existing report reference', false), f.recorded('allegation_case_reference', 'Secure allegation case reference')],
  },
  {
    key: 'safeguarding_training', name: 'Safeguarding training record', category: 'Safeguarding',
    summary: 'Required training checked before someone starts a role and renewal followed up.',
    audience: 'For teams tracking safeguarding training for staff and volunteers.', outcome: 'A training record and its next review date are verified.',
    respondents: 'A staff member, volunteer or team leader.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Training verification', byRole: 'safeguarding_lead', dueInHours: 72 }],
    task: { key: 'update_training_register', name: 'Update the training register', byRole: 'safeguarding_lead', description: 'Verify the course completion with the approved source and record the register reference and renewal date.', requiredFields: ['training_register_reference'] },
    completionMessage: 'The safeguarding training record has been verified.', retentionDays: 2555,
    fields: [f.person('worker_name', 'Worker name'), f.text('worker_role', 'Role or team'), f.text('course_name', 'Training course'), f.date('completed_on', 'Date completed'), f.text('certificate_reference', 'Certificate or provider reference', false), { ...f.date('renewal_due', 'Renewal due date', false), setBy: 'operator' }, f.recorded('training_register_reference', 'Training register reference')],
  },
  {
    key: 'safeguarding_clearance', name: 'Role clearance review', category: 'Safeguarding',
    summary: 'A person’s checks, references and training reviewed before they enter a protected role.',
    audience: 'For organisations assigning people to work with children or vulnerable adults.', outcome: 'A named lead records clearance or a reason not to start.',
    respondents: 'A team leader requesting role clearance.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Safeguarding clearance', byRole: 'safeguarding_lead', dueInHours: 72 }],
    task: { key: 'record_clearance', name: 'Record the role decision', byRole: 'safeguarding_lead', description: 'Check the required screening, references, training and local policy; record the decision by reference without uploading certificate copies.', requiredFields: ['clearance_decision_reference'] },
    completionMessage: 'The role clearance decision has been recorded.', notes: ['A request does not authorise the person to start. Screening requirements depend on the role and jurisdiction.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('worker_name', 'Person to be cleared'), f.text('proposed_role', 'Proposed role'), f.date('planned_start', 'Planned start date'), f.choice('contact_group', 'Who will the role involve?', ['children', 'vulnerable_adults', 'both', 'other']), f.text('screening_reference', 'Existing screening reference', false), f.text('training_reference', 'Training reference', false), f.private('review_notes', 'Anything the safeguarding lead should know?', 'Role clearance details are restricted to the safeguarding team.'), f.recorded('clearance_decision_reference', 'Clearance decision reference')],
  },

  // Sales
  {
    key: 'demo_request', name: 'Product demo request', category: 'Sales',
    summary: 'A prospect’s demo request qualified and scheduled with a clear follow-up.',
    audience: 'For sales teams arranging product demonstrations.', outcome: 'The demo is scheduled or declined with a reason.',
    respondents: 'A prospective customer.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales triage', byRole: 'sales_lead', dueInHours: 24 }],
    task: { key: 'schedule_demo', name: 'Schedule the demo', byRole: 'sales_lead', description: 'Confirm the use case, invite the right presenter and send the agreed meeting details.', requiredFields: ['demo_booking_reference'] },
    completionMessage: 'The demo request has been reviewed and the next step recorded.', retentionDays: 1825,
    fields: [f.text('organisation', 'Organisation', false), f.choice('product_area', 'What would you like to see?', ['core_product', 'integrations', 'reporting', 'pricing']), f.notes('use_case', 'What are you trying to do?'), f.choice('team_size', 'Team size', ['one_to_ten', 'eleven_to_fifty', 'fifty_plus']), f.date('preferred_date', 'Preferred date'), f.phone('contact_phone', 'Phone number', false), f.recorded('demo_booking_reference', 'Demo booking reference')],
  },
  {
    key: 'discount_approval', name: 'Discount approval', category: 'Sales',
    summary: 'A proposed discount checked against margin and authorised before a quote is sent.',
    audience: 'For sales teams with delegated pricing limits.', outcome: 'The authorised price and reason are recorded against the deal.',
    respondents: 'A sales representative.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales manager', byRole: 'sales_lead', dueInHours: 24 }, { key: 'finance', name: 'Margin check', byRole: 'finance_reviewer', dueInHours: 48 }],
    task: { key: 'record_price', name: 'Update the approved quote', byRole: 'process_owner', description: 'Use the approved price and expiry in the quoting system, then record the revised quote reference.', requiredFields: ['discounted_quote_reference'] },
    completionMessage: 'The approved discount has been recorded in the revised quote.', notes: ['Configure your actual delegation thresholds and margin rules before publishing.'], retentionDays: 1825,
    fields: [f.text('deal_reference', 'Deal reference'), f.text('customer_name', 'Customer'), f.money('list_price', 'Standard price'), f.money('proposed_price', 'Proposed price'), f.notes('discount_reason', 'Why is the discount needed?'), f.date('offer_expires', 'Offer expiry'), f.recorded('discounted_quote_reference', 'Revised quote reference')],
  },
  {
    key: 'sales_order_review', name: 'Sales order review', category: 'Sales',
    summary: 'A customer order checked against quote, capacity and delivery terms before acceptance.',
    audience: 'For sales teams handing an order to operations.', outcome: 'The order is accepted and handed off with a reference.',
    respondents: 'A sales representative or account owner.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales review', byRole: 'sales_lead', dueInHours: 24 }, { key: 'delivery', name: 'Delivery capacity', byRole: 'delivery_lead', dueInHours: 48 }],
    task: { key: 'book_order', name: 'Book and hand over the order', byRole: 'process_owner', description: 'Confirm the approved quote and terms, enter the order in the sales system and hand the delivery details to operations.', requiredFields: ['sales_order_reference'] },
    completionMessage: 'The accepted sales order and delivery handover have been recorded.', retentionDays: 1825,
    fields: [f.text('customer_name', 'Customer'), f.text('quote_reference', 'Approved quote reference'), f.notes('products_or_services', 'Products or services ordered'), f.money('order_value', 'Order value'), f.date('delivery_by', 'Requested delivery date'), f.text('purchase_order_number', 'Customer PO number', false), f.recorded('sales_order_reference', 'Sales order reference')],
  },
  {
    key: 'lead_qualification', name: 'Lead qualification', category: 'Sales',
    summary: 'An inbound lead assessed and routed to a named owner for a next conversation.',
    audience: 'For sales teams receiving enquiries from several channels.', outcome: 'The lead is qualified or declined with an owner and next action.',
    respondents: 'A prospective customer or sales team member.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales triage', byRole: 'sales_lead', dueInHours: 24 }],
    task: { key: 'assign_lead', name: 'Assign owner and next action', byRole: 'process_owner', description: 'Check fit, contact preference and consent, assign an account owner and record the next action in the CRM.', requiredFields: ['crm_lead_reference'] },
    completionMessage: 'Your enquiry has been reviewed and the next action recorded.', retentionDays: 1825,
    fields: [f.text('organisation', 'Organisation', false), f.choice('interest_area', 'Area of interest', ['product', 'service', 'partnership', 'other']), f.notes('business_need', 'What are you looking for?'), f.choice('timeline', 'When are you looking to start?', ['now', 'this_quarter', 'later', 'exploring']), f.choice('contact_preference', 'How should we contact you?', ['email', 'phone']), f.yesNo('contact_permission', 'May the sales team contact you about this enquiry?'), f.recorded('crm_lead_reference', 'CRM lead reference')],
  },
];
