/**
 * The catalogue.
 *
 * Each entry says only what makes that process different; the shape they all
 * share is generated in `generate.ts`. Categories follow how an organization
 * is actually arranged — somebody looking for a leave request looks under
 * People, not under "Forms".
 *
 * Every one of these compiles, and `npm run packs:check` fails the build if
 * one stops. A template that does not compile is worse than no template: it
 * teaches somebody that the compiler is an obstacle rather than a check.
 */

import type { PackSpec } from './generate.js';

const f = {
  text: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'short_text',
    required,
    classification: 'internal' as const,
  }),
  person: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'short_text',
    required,
    classification: 'confidential' as const,
  }),
  email: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'email',
    required,
    classification: 'confidential' as const,
  }),
  phone: (key: string, label: string, required = false) => ({
    key,
    label,
    type: 'phone',
    required,
    classification: 'confidential' as const,
  }),
  notes: (key: string, label: string, required = false) => ({
    key,
    label,
    type: 'long_text',
    required,
    classification: 'confidential' as const,
  }),
  money: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'currency',
    required,
    classification: 'confidential' as const,
  }),
  number: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'number',
    required,
    classification: 'internal' as const,
  }),
  date: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'date',
    required,
    classification: 'internal' as const,
  }),
  time: (key: string, label: string, required = false) => ({
    key,
    label,
    type: 'time',
    required,
    classification: 'internal' as const,
  }),
  yesNo: (key: string, label: string, required = true) => ({
    key,
    label,
    type: 'yes_no',
    required,
    classification: 'internal' as const,
  }),
  choice: (key: string, label: string, choices: string[], required = true) => ({
    key,
    label,
    type: 'dropdown',
    required,
    choices,
    classification: 'internal' as const,
  }),
  many: (key: string, label: string, choices: string[], required = false) => ({
    key,
    label,
    type: 'multi_choice',
    required,
    choices,
    classification: 'internal' as const,
  }),
  rating: (key: string, label: string, required = false) => ({
    key,
    label,
    type: 'rating',
    required,
    classification: 'internal' as const,
  }),
  url: (key: string, label: string, required = false) => ({
    key,
    label,
    type: 'url',
    required,
    classification: 'internal' as const,
  }),
  /**
   * Restricted fields carry a reason, because the compiler refuses one
   * without — and because a field nobody can justify is a field nobody should
   * be collecting.
   */
  sensitive: (key: string, label: string, reason: string, required = true) => ({
    key,
    label,
    type: 'short_text',
    required,
    classification: 'restricted' as const,
    reason,
  }),
};

export const CATALOGUE: PackSpec[] = [
  // ------------------------------------------------------------- People
  {
    key: 'leave_request',
    name: 'Leave request',
    category: 'People',
    summary: 'Time off asked for, checked against the team calendar, and approved by a line manager.',
    audience: 'For any team still approving holiday over email or chat.',
    outcome: 'A period of leave is approved, recorded, and visible to whoever needs to plan around it.',
    respondents: 'Anybody employed here.',
    ownerName: 'People team',
    approvals: [{ key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 48 }],
    retentionDays: 2555,
    volume: { count: 200, per: 'month' },
    fields: [
      f.choice('leave_type', 'Kind of leave', ['annual', 'sick', 'parental', 'compassionate', 'unpaid']),
      f.date('starts_on', 'First day off'),
      f.date('ends_on', 'Last day off'),
      f.number('working_days', 'Working days this uses'),
      f.person('cover_name', 'Who is covering', false),
      f.notes('leave_note', 'Anything your manager should know', false),
    ],
  },
  {
    key: 'expense_claim',
    name: 'Expense claim',
    category: 'Finance',
    summary: 'Money spent, checked against its receipts, approved at the right level and sent to payroll.',
    audience: 'For a finance team approving expenses over email.',
    outcome: 'A claim is checked, approved and queued for payment, with the evidence attached to the record.',
    respondents: 'Any member of staff claiming money back.',
    ownerName: 'Finance',
    approvals: [
      { key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 72 },
      { key: 'finance', name: 'Finance check', byRole: 'finance_reviewer', dueInHours: 120 },
    ],
    retentionDays: 2555,
    volume: { count: 300, per: 'month' },
    fields: [
      f.date('spent_on', 'Date of the expense'),
      f.money('amount', 'Amount'),
      f.choice('expense_category', 'Category', ['travel', 'subsistence', 'equipment', 'software', 'other']),
      f.text('cost_centre', 'Cost centre'),
      f.notes('business_purpose', 'What it was for', true),
      f.yesNo('has_receipt', 'Do you have a receipt?'),
    ],
  },
  {
    key: 'new_starter',
    name: 'New starter onboarding',
    category: 'People',
    summary: 'From an accepted offer to a first day that works: approvals, equipment, accounts and access.',
    audience: 'For an HR or operations team hiring regularly.',
    outcome: 'A new joiner starts with the right equipment, accounts and access on their first day.',
    respondents: 'The hiring manager, after an offer is accepted.',
    ownerName: 'People team',
    approvals: [
      { key: 'hiring_manager', name: 'Hiring manager', byRole: 'hiring_manager', dueInHours: 48 },
      { key: 'hr', name: 'HR check', byRole: 'hr_reviewer', dueInHours: 72 },
    ],
    task: { key: 'provision', name: 'Equipment and accounts', byRole: 'it_operator' },
    retentionDays: 2555,
    fields: [
      f.person('joiner_name', 'Their name'),
      f.email('joiner_email', 'Their personal email'),
      f.date('start_date', 'First day'),
      f.text('job_title', 'Job title'),
      f.choice('work_pattern', 'Work pattern', ['full_time', 'part_time', 'fixed_term', 'contract']),
      f.many('equipment', 'Equipment needed', ['laptop', 'monitor', 'phone', 'headset', 'none']),
    ],
  },
  {
    key: 'leaver_offboarding',
    name: 'Leaver offboarding',
    category: 'People',
    summary: 'Access removed, equipment returned, final pay confirmed — with a record that each happened.',
    audience: 'For any organization that has to prove access was revoked.',
    outcome: 'Somebody leaves with every account closed, every asset returned and a record of both.',
    respondents: 'The line manager, once a resignation is confirmed.',
    ownerName: 'People team',
    approvals: [{ key: 'hr', name: 'HR confirmation', byRole: 'hr_reviewer', dueInHours: 48 }],
    task: { key: 'revoke', name: 'Close accounts and collect equipment', byRole: 'it_operator' },
    retentionDays: 2555,
    fields: [
      f.person('leaver_name', 'Who is leaving'),
      f.date('last_day', 'Last working day'),
      f.choice('leaving_reason', 'Reason', ['resignation', 'end_of_contract', 'retirement', 'dismissal', 'other']),
      f.many('assets_held', 'What they hold', ['laptop', 'phone', 'keys', 'card', 'none']),
      f.yesNo('handover_done', 'Has handover been agreed?'),
    ],
  },
  {
    key: 'recruitment_request',
    name: 'Request to hire',
    category: 'People',
    summary: 'A vacancy justified, budgeted and approved before any advert goes out.',
    audience: 'For an organization where headcount needs sign-off.',
    outcome: 'A role is approved to advertise, with its budget and justification recorded.',
    respondents: 'A manager who needs somebody.',
    ownerName: 'People team',
    approvals: [
      { key: 'department', name: 'Department head', byRole: 'department_head', dueInHours: 72 },
      { key: 'finance', name: 'Budget check', byRole: 'finance_reviewer', dueInHours: 120 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('role_title', 'Role title'),
      f.text('department', 'Department'),
      f.money('salary_budget', 'Budgeted salary'),
      f.choice('contract_type', 'Contract', ['permanent', 'fixed_term', 'contract', 'intern']),
      f.notes('why_needed', 'Why this role is needed', true),
      f.yesNo('replacement', 'Is this replacing somebody?'),
    ],
  },
  {
    key: 'performance_review',
    name: 'Performance review',
    category: 'People',
    summary: 'A review cycle that actually closes: self-assessment, manager response, and a recorded outcome.',
    audience: 'For a team whose review cycle keeps slipping.',
    outcome: 'A review is completed, agreed and recorded for both parties.',
    respondents: 'Every member of staff, at review time.',
    ownerName: 'People team',
    approvals: [{ key: 'manager', name: 'Manager sign-off', byRole: 'line_manager', dueInHours: 168 }],
    retentionDays: 2555,
    fields: [
      f.choice('review_period', 'Period', ['h1', 'h2', 'annual']),
      f.notes('achievements', 'What went well', true),
      f.notes('development', 'What you want to get better at', true),
      f.rating('self_rating', 'How you would rate the period'),
      f.notes('support_needed', 'What support you need', false),
    ],
  },
  {
    key: 'training_request',
    name: 'Training request',
    category: 'People',
    summary: 'A course or conference justified against a budget and approved before anybody books.',
    audience: 'For a team with a learning budget and no way to track it.',
    outcome: 'Training is approved with its cost recorded against a budget.',
    respondents: 'Anybody wanting to learn something.',
    ownerName: 'People team',
    approvals: [{ key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 96 }],
    retentionDays: 1095,
    fields: [
      f.text('course_name', 'What the training is'),
      f.url('course_link', 'Link to it'),
      f.money('course_cost', 'Cost'),
      f.date('course_date', 'When it happens'),
      f.notes('course_reason', 'How this helps your work', true),
    ],
  },
  {
    key: 'grievance',
    name: 'Grievance',
    category: 'People',
    summary: 'A formal complaint received, acknowledged within a day, and routed away from the people named in it.',
    audience: 'For any employer with a duty to handle these properly.',
    outcome: 'A grievance is investigated and concluded, with every step timestamped.',
    respondents: 'Any member of staff.',
    ownerName: 'HR case team',
    approvals: [{ key: 'hr_lead', name: 'HR lead', byRole: 'hr_case_lead', dueInHours: 24 }],
    task: { key: 'investigate', name: 'Investigation', byRole: 'hr_case_lead' },
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('grievance_type', 'What this concerns', ['conduct', 'pay', 'workload', 'discrimination', 'other']),
      f.notes('what_happened', 'What happened', true),
      f.date('happened_on', 'When'),
      f.sensitive(
        'people_involved',
        'Who was involved',
        'Needed to route the case away from anybody named in it, and to conduct the investigation.',
        false,
      ),
      f.yesNo('raised_before', 'Have you raised this before?'),
    ],
  },
  {
    key: 'dbs_check',
    name: 'Background check',
    category: 'People',
    summary: 'A vetting check recorded as a reference and a date — never as a stored copy of the certificate.',
    audience: 'For anybody whose staff or volunteers work with children or vulnerable adults.',
    outcome: 'A check is confirmed, recorded by reference, and due for renewal on a known date.',
    respondents: 'A new member of staff or volunteer.',
    ownerName: 'Safeguarding team',
    approvals: [{ key: 'safeguarding', name: 'Safeguarding lead', byRole: 'safeguarding_lead', dueInHours: 72 }],
    retentionDays: 1825,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('check_level', 'Level of check', ['basic', 'standard', 'enhanced']),
      f.sensitive(
        'certificate_number',
        'Certificate number',
        'Recorded as a reference so the certificate itself is never stored. Required to verify the check with the issuing body.',
      ),
      f.date('issued_on', 'Date on the certificate'),
      f.person('checked_by', 'Who verified it'),
    ],
  },
  {
    key: 'reference_request',
    name: 'Reference request',
    category: 'People',
    summary: 'A reference asked for, chased if it does not arrive, and closed either way.',
    audience: 'For anybody who has ever waited three weeks for a reference.',
    outcome: 'A reference is received or formally closed as unobtainable.',
    respondents: 'A recruiter or hiring manager.',
    ownerName: 'People team',
    approvals: [{ key: 'hr', name: 'HR review', byRole: 'hr_reviewer', dueInHours: 120 }],
    retentionDays: 1095,
    fields: [
      f.person('candidate_name', 'Candidate'),
      f.person('referee_name', 'Referee'),
      f.email('referee_email', 'Referee email'),
      f.text('relationship', 'How they know each other'),
      f.choice('reference_kind', 'Kind', ['employment', 'character', 'academic']),
    ],
  },

  // ------------------------------------------------------------ Finance
  {
    key: 'purchase_request',
    name: 'Purchase request',
    category: 'Finance',
    summary: 'Something bought only after somebody with a budget agreed to it.',
    audience: 'For an organization where spending happens before anybody checks.',
    outcome: 'A purchase is approved against a budget, with a record of who agreed.',
    respondents: 'Anybody who needs to buy something.',
    ownerName: 'Finance',
    approvals: [
      { key: 'budget_holder', name: 'Budget holder', byRole: 'budget_holder', dueInHours: 72 },
      { key: 'finance', name: 'Finance check', byRole: 'finance_reviewer', dueInHours: 120 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('item', 'What you want to buy'),
      f.money('estimated_cost', 'Estimated cost'),
      f.text('supplier', 'Supplier', false),
      f.text('budget_code', 'Budget code'),
      f.notes('purchase_reason', 'Why it is needed', true),
      f.choice('urgency', 'How soon', ['this_week', 'this_month', 'this_quarter']),
    ],
  },
  {
    key: 'invoice_approval',
    name: 'Invoice approval',
    category: 'Finance',
    summary: 'An invoice matched to what was ordered, approved, and queued for payment.',
    audience: 'For a finance team chasing approvals by email.',
    outcome: 'An invoice is approved for payment with the approval recorded against it.',
    respondents: 'Accounts payable, or whoever receives the invoice.',
    ownerName: 'Finance',
    approvals: [{ key: 'budget_holder', name: 'Budget holder', byRole: 'budget_holder', dueInHours: 96 }],
    retentionDays: 2555,
    fields: [
      f.text('invoice_number', 'Invoice number'),
      f.text('supplier_name', 'Supplier'),
      f.money('invoice_amount', 'Amount'),
      f.date('invoice_date', 'Invoice date'),
      f.date('due_date', 'Payment due'),
      f.text('po_number', 'Purchase order, if there is one', false),
    ],
  },
  {
    key: 'budget_transfer',
    name: 'Budget transfer',
    category: 'Finance',
    summary: 'Money moved between cost centres with both sides agreeing in writing.',
    audience: 'For an organization with departmental budgets.',
    outcome: 'A transfer is agreed by both budget holders and recorded.',
    respondents: 'A budget holder.',
    ownerName: 'Finance',
    approvals: [
      { key: 'from_holder', name: 'Losing budget holder', byRole: 'budget_holder', dueInHours: 72 },
      { key: 'finance', name: 'Finance', byRole: 'finance_reviewer', dueInHours: 96 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('from_code', 'From budget code'),
      f.text('to_code', 'To budget code'),
      f.money('transfer_amount', 'Amount'),
      f.notes('transfer_reason', 'Why', true),
    ],
  },
  {
    key: 'mileage_claim',
    name: 'Mileage claim',
    category: 'Finance',
    summary: 'Business travel claimed at the right rate, with the journey recorded.',
    audience: 'For anybody whose staff drive for work.',
    outcome: 'Mileage is approved at the correct rate and sent to payroll.',
    respondents: 'Any member of staff who drove for work.',
    ownerName: 'Finance',
    approvals: [{ key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 72 }],
    retentionDays: 2555,
    fields: [
      f.date('journey_date', 'Date of the journey'),
      f.text('journey_from', 'From'),
      f.text('journey_to', 'To'),
      f.number('miles', 'Miles'),
      f.choice('vehicle', 'Vehicle', ['own_car', 'company_car', 'motorcycle', 'bicycle']),
      f.notes('journey_purpose', 'Purpose', true),
    ],
  },
  {
    key: 'petty_cash',
    name: 'Petty cash',
    category: 'Finance',
    summary: 'Small cash spending recorded rather than reconstructed at year end.',
    audience: 'For an office, site or branch holding a cash float.',
    outcome: 'A cash payment is recorded, approved and reconciled.',
    respondents: 'Whoever spent the cash.',
    ownerName: 'Finance',
    approvals: [{ key: 'office_manager', name: 'Office manager', byRole: 'office_manager', dueInHours: 48 }],
    retentionDays: 2555,
    fields: [
      f.money('cash_amount', 'Amount'),
      f.date('cash_date', 'Date'),
      f.text('cash_what', 'What it was for'),
      f.yesNo('receipt_attached', 'Receipt kept?'),
    ],
  },
  {
    key: 'refund_request',
    name: 'Refund request',
    category: 'Finance',
    summary: 'A customer refund assessed against policy and either paid or explained.',
    audience: 'For anybody selling to the public.',
    outcome: 'A refund is decided against policy and the customer is told either way.',
    respondents: 'A customer, or an agent on their behalf.',
    ownerName: 'Customer operations',
    approvals: [{ key: 'supervisor', name: 'Supervisor', byRole: 'support_supervisor', dueInHours: 48 }],
    retentionDays: 2190,
    fields: [
      f.text('order_reference', 'Order reference'),
      f.money('refund_amount', 'Amount requested'),
      f.choice('refund_reason', 'Reason', ['faulty', 'not_as_described', 'late', 'changed_mind', 'other']),
      f.notes('refund_detail', 'Anything else we should know', false),
    ],
  },

  // ---------------------------------------------------------------- IT
  {
    key: 'it_support',
    name: 'IT support ticket',
    category: 'IT',
    summary: 'A problem reported, triaged by urgency, and closed with what fixed it.',
    audience: 'For an IT team taking requests by tap on the shoulder.',
    outcome: 'A reported problem is resolved and the fix is recorded.',
    respondents: 'Anybody with a problem.',
    ownerName: 'IT service desk',
    approvals: [{ key: 'triage', name: 'Triage', byRole: 'it_operator', dueInHours: 8 }],
    task: { key: 'fix', name: 'Fix it', byRole: 'it_operator' },
    retentionDays: 730,
    volume: { count: 400, per: 'month' },
    fields: [
      f.choice('problem_kind', 'What kind of problem', ['hardware', 'software', 'access', 'network', 'other']),
      f.notes('problem_detail', 'What is happening', true),
      f.choice('impact', 'Who it affects', ['just_me', 'my_team', 'everybody']),
      f.yesNo('blocking_work', 'Is this stopping you working?'),
    ],
  },
  {
    key: 'access_request',
    name: 'System access request',
    category: 'IT',
    summary: 'Access to a system granted by the data owner, not by whoever happens to be free.',
    audience: 'For anybody who has to prove who approved access, to an auditor.',
    outcome: 'Access is granted by the right owner, recorded, and revocable.',
    respondents: 'Any member of staff needing access.',
    ownerName: 'IT service desk',
    approvals: [
      { key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 48 },
      { key: 'system_owner', name: 'System owner', byRole: 'system_owner', dueInHours: 72 },
    ],
    task: { key: 'grant', name: 'Grant the access', byRole: 'it_operator' },
    retentionDays: 2555,
    fields: [
      f.text('system_name', 'Which system'),
      f.choice('access_level', 'Level', ['read', 'write', 'admin']),
      f.notes('access_reason', 'Why you need it', true),
      f.date('needed_until', 'Needed until', false),
    ],
  },
  {
    key: 'equipment_request',
    name: 'Equipment request',
    category: 'IT',
    summary: 'Hardware asked for, approved against a budget, and tracked to the person holding it.',
    audience: 'For a team that cannot say who has which laptop.',
    outcome: 'Equipment is approved, issued and recorded against a person.',
    respondents: 'Any member of staff.',
    ownerName: 'IT service desk',
    approvals: [{ key: 'manager', name: 'Line manager', byRole: 'line_manager', dueInHours: 72 }],
    task: { key: 'issue', name: 'Issue the equipment', byRole: 'it_operator' },
    retentionDays: 1825,
    fields: [
      f.choice('equipment_kind', 'What you need', ['laptop', 'monitor', 'phone', 'headset', 'accessory']),
      f.notes('equipment_reason', 'Why', true),
      f.yesNo('replacing_existing', 'Is this replacing something?'),
    ],
  },
  {
    key: 'change_request',
    name: 'Change request',
    category: 'IT',
    summary: 'A change to a live system reviewed, scheduled, and recorded with a way back.',
    audience: 'For a team that needs a change record for its auditors.',
    outcome: 'A change is approved, made in a window, and recorded with its rollback.',
    respondents: 'An engineer or supplier.',
    ownerName: 'Change management',
    approvals: [
      { key: 'technical', name: 'Technical review', byRole: 'system_owner', dueInHours: 48 },
      { key: 'cab', name: 'Change board', byRole: 'change_board', dueInHours: 120 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('system_changed', 'Which system'),
      f.notes('change_detail', 'What is changing', true),
      f.choice('change_risk', 'Risk', ['low', 'medium', 'high']),
      f.date('change_window', 'When'),
      f.notes('rollback_plan', 'How it is undone if it goes wrong', true),
    ],
  },
  {
    key: 'incident_report',
    name: 'IT incident',
    category: 'IT',
    summary: 'An outage logged the moment it starts, with the timeline that a review will need.',
    audience: 'For anybody who has written a post-incident review from memory.',
    outcome: 'An incident is resolved and reviewed, with its timeline intact.',
    respondents: 'Anybody who noticed.',
    ownerName: 'IT service desk',
    approvals: [{ key: 'incident_lead', name: 'Incident lead', byRole: 'it_operator', dueInHours: 4 }],
    task: { key: 'review', name: 'Post-incident review', byRole: 'it_operator' },
    retentionDays: 1825,
    fields: [
      f.text('affected_service', 'What is affected'),
      f.choice('severity', 'Severity', ['sev1', 'sev2', 'sev3', 'sev4']),
      f.notes('incident_detail', 'What is happening', true),
      f.date('started_on', 'When it started'),
      f.time('started_at', 'Roughly what time'),
    ],
  },

  // ------------------------------------------------------ Facilities
  {
    key: 'maintenance_request',
    name: 'Maintenance request',
    category: 'Facilities',
    summary: 'Something broken reported, prioritised by safety, and closed when it is fixed.',
    audience: 'For anybody running a building.',
    outcome: 'A fault is fixed and the fix is recorded against the location.',
    respondents: 'Anybody using the building.',
    ownerName: 'Facilities',
    approvals: [{ key: 'facilities', name: 'Facilities triage', byRole: 'facilities_lead', dueInHours: 24 }],
    task: { key: 'repair', name: 'Carry out the repair', byRole: 'facilities_lead' },
    retentionDays: 1825,
    fields: [
      f.text('location', 'Where it is'),
      f.notes('fault_detail', 'What is wrong', true),
      f.choice('fault_urgency', 'Urgency', ['safety_risk', 'unusable', 'inconvenient']),
      f.yesNo('area_closed', 'Has the area been closed off?'),
    ],
  },
  {
    key: 'room_booking',
    name: 'Room or space booking',
    category: 'Facilities',
    summary: 'A space requested, checked for clashes, and confirmed with whoever needs to open up.',
    audience: 'For anybody whose rooms are double-booked in a shared calendar.',
    outcome: 'A space is confirmed for a date and time, with the setup arranged.',
    respondents: 'Anybody needing a room.',
    ownerName: 'Facilities',
    approvals: [{ key: 'facilities', name: 'Facilities', byRole: 'facilities_lead', dueInHours: 24 }],
    retentionDays: 365,
    fields: [
      f.text('space_wanted', 'Which space'),
      f.date('booking_date', 'Date'),
      f.time('booking_start', 'From'),
      f.time('booking_end', 'Until'),
      f.number('attendees', 'How many people'),
      f.many('setup_needed', 'Setup', ['projector', 'chairs', 'catering', 'accessible_access', 'none']),
    ],
  },
  {
    key: 'visitor_request',
    name: 'Visitor request',
    category: 'Facilities',
    summary: 'A visitor expected, with reception told and a host named before they arrive.',
    audience: 'For any site with a signing-in book and a fire list.',
    outcome: 'A visitor is expected, hosted and signed out.',
    respondents: 'Whoever is hosting.',
    ownerName: 'Reception',
    approvals: [{ key: 'reception', name: 'Reception', byRole: 'office_manager', dueInHours: 24 }],
    retentionDays: 365,
    fields: [
      f.person('visitor_name', 'Visitor name'),
      f.text('visitor_company', 'Company', false),
      f.date('visit_date', 'Date'),
      f.time('visit_time', 'Expected time'),
      f.yesNo('needs_parking', 'Do they need parking?'),
    ],
  },
  {
    key: 'asset_disposal',
    name: 'Asset disposal',
    category: 'Facilities',
    summary: 'Equipment written off with its data wiped and the wipe recorded.',
    audience: 'For anybody disposing of devices that held customer data.',
    outcome: 'An asset is disposed of, with proof its data was destroyed.',
    respondents: 'IT or facilities.',
    ownerName: 'Facilities',
    approvals: [
      { key: 'manager', name: 'Asset owner', byRole: 'line_manager', dueInHours: 72 },
      { key: 'it', name: 'Data destruction check', byRole: 'it_operator', dueInHours: 96 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('asset_tag', 'Asset tag'),
      f.text('asset_kind', 'What it is'),
      f.choice('disposal_route', 'How it is going', ['recycled', 'sold', 'donated', 'destroyed']),
      f.yesNo('data_wiped', 'Has the data been destroyed?'),
    ],
  },

  // ------------------------------------------------------- Customer
  {
    key: 'complaint',
    name: 'Customer complaint',
    category: 'Customer',
    summary: 'A complaint acknowledged the same day, investigated, and answered within a deadline.',
    audience: 'For anybody with a regulator watching their complaint handling.',
    outcome: 'A complaint is investigated and answered within the deadline, with the timeline recorded.',
    respondents: 'A customer.',
    ownerName: 'Customer operations',
    approvals: [{ key: 'supervisor', name: 'Complaints supervisor', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'investigate', name: 'Investigate', byRole: 'support_supervisor' },
    retentionDays: 2190,
    fields: [
      f.choice('complaint_about', 'What this is about', ['service', 'product', 'billing', 'staff', 'other']),
      f.notes('complaint_detail', 'What happened', true),
      f.date('happened_on', 'When'),
      f.text('order_reference', 'Order or account reference', false),
      f.choice('outcome_wanted', 'What would put it right', ['refund', 'replacement', 'apology', 'explanation']),
    ],
  },
  {
    key: 'feedback',
    name: 'Feedback',
    category: 'Customer',
    summary: 'A suggestion captured, read by somebody, and answered rather than lost in a mailbox.',
    audience: 'For anybody whose feedback form goes to a shared inbox.',
    outcome: 'Feedback reaches somebody who can act on it, and the sender is told what happened.',
    respondents: 'Anybody.',
    ownerName: 'Customer operations',
    approvals: [{ key: 'triage', name: 'Triage', byRole: 'support_supervisor', dueInHours: 72 }],
    retentionDays: 1095,
    fields: [
      f.choice('feedback_kind', 'Kind', ['compliment', 'suggestion', 'problem']),
      f.notes('feedback_detail', 'Tell us', true),
      f.rating('satisfaction', 'How would you rate us'),
      f.yesNo('reply_wanted', 'Would you like a reply?'),
    ],
  },
  {
    key: 'quote_request',
    name: 'Quote request',
    category: 'Sales',
    summary: 'An enquiry qualified, priced and sent, with a chase if nobody responds.',
    audience: 'For a sales team losing enquiries in a shared inbox.',
    outcome: 'An enquiry becomes a priced quote that was actually sent.',
    respondents: 'A prospective customer.',
    ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales review', byRole: 'sales_lead', dueInHours: 24 }],
    task: { key: 'price_it', name: 'Prepare the quote', byRole: 'sales_lead' },
    retentionDays: 1825,
    fields: [
      f.text('company_name', 'Company', false),
      f.phone('contact_phone', 'Phone'),
      f.notes('what_needed', 'What you need', true),
      f.choice('needed_by', 'When', ['this_week', 'this_month', 'this_quarter', 'exploring']),
      f.money('budget_range', 'Rough budget', false),
    ],
  },
  {
    key: 'contract_review',
    name: 'Contract review',
    category: 'Legal',
    summary: 'A contract read by legal before anybody signs, with the version reviewed recorded.',
    audience: 'For anybody who has signed something legal had not seen.',
    outcome: 'A contract is reviewed, amended if needed, and approved to sign.',
    respondents: 'Whoever holds the relationship.',
    ownerName: 'Legal',
    approvals: [
      { key: 'legal', name: 'Legal review', byRole: 'legal_reviewer', dueInHours: 120 },
      { key: 'signatory', name: 'Authorised signatory', byRole: 'department_head', dueInHours: 96 },
    ],
    retentionDays: 3650,
    fields: [
      f.text('counterparty', 'Who it is with'),
      f.choice('contract_kind', 'Kind', ['supplier', 'customer', 'nda', 'lease', 'employment', 'other']),
      f.money('contract_value', 'Value', false),
      f.date('needed_by', 'Needed by'),
      f.notes('contract_summary', 'What it commits us to', true),
    ],
  },
  {
    key: 'supplier_onboarding',
    name: 'Supplier onboarding',
    category: 'Procurement',
    summary: 'A new supplier checked for insurance, compliance and bank details before the first invoice.',
    audience: 'For anybody who has paid an invoice to the wrong bank account.',
    outcome: 'A supplier is approved, with its checks recorded and its details verified.',
    respondents: 'Whoever wants to use the supplier.',
    ownerName: 'Procurement',
    approvals: [
      { key: 'procurement', name: 'Procurement check', byRole: 'procurement_lead', dueInHours: 120 },
      { key: 'finance', name: 'Finance check', byRole: 'finance_reviewer', dueInHours: 120 },
    ],
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.text('supplier_name', 'Supplier name'),
      f.email('supplier_email', 'Their contact email'),
      f.text('registration_number', 'Company registration number', false),
      f.sensitive(
        'bank_reference',
        'Bank verification reference',
        'The reference from an independent bank verification. The account details themselves are never stored here.',
        false,
      ),
      f.yesNo('insurance_seen', 'Have you seen their insurance?'),
      f.notes('what_they_supply', 'What they supply', true),
    ],
  },

  // ---------------------------------------------------- Health & safety
  {
    key: 'accident_report',
    name: 'Accident report',
    category: 'Health & safety',
    summary: 'An injury recorded within the hour, with the detail a regulator will ask for.',
    audience: 'For any employer with a legal duty to record accidents.',
    outcome: 'An accident is recorded, investigated, and reported onward where the law requires it.',
    respondents: 'Anybody who was there.',
    ownerName: 'Health and safety',
    approvals: [{ key: 'hs_lead', name: 'Health and safety lead', byRole: 'safety_lead', dueInHours: 24 }],
    task: { key: 'investigate', name: 'Investigate', byRole: 'safety_lead' },
    retentionDays: 3650,
    sensitivityCeiling: 'restricted',
    fields: [
      f.date('accident_date', 'Date'),
      f.time('accident_time', 'Time'),
      f.text('accident_location', 'Where'),
      f.notes('accident_detail', 'What happened', true),
      f.sensitive(
        'injury_detail',
        'Injury',
        'A legal requirement under accident reporting rules, and needed to decide whether it is reportable to the regulator.',
        false,
      ),
      f.yesNo('first_aid_given', 'Was first aid given?'),
    ],
  },
  {
    key: 'near_miss',
    name: 'Near miss',
    category: 'Health & safety',
    summary: 'Something that almost went wrong, captured while somebody still remembers it.',
    audience: 'For any site that wants to fix hazards before they cause an injury.',
    outcome: 'A hazard is recorded and acted on before it causes harm.',
    respondents: 'Anybody who saw it.',
    ownerName: 'Health and safety',
    approvals: [{ key: 'hs_lead', name: 'Health and safety lead', byRole: 'safety_lead', dueInHours: 48 }],
    retentionDays: 1825,
    fields: [
      f.date('near_miss_date', 'Date'),
      f.text('near_miss_where', 'Where'),
      f.notes('near_miss_detail', 'What nearly happened', true),
      f.choice('could_have_been', 'What it could have caused', ['minor', 'serious', 'life_changing']),
    ],
  },
  {
    key: 'risk_assessment',
    name: 'Risk assessment',
    category: 'Health & safety',
    summary: 'An activity assessed, its controls agreed, and a review date set.',
    audience: 'For anybody running events, trips or physical work.',
    outcome: 'An activity is assessed, its controls are agreed, and it has a review date.',
    respondents: 'Whoever is running the activity.',
    ownerName: 'Health and safety',
    approvals: [{ key: 'hs_lead', name: 'Health and safety lead', byRole: 'safety_lead', dueInHours: 120 }],
    retentionDays: 1825,
    fields: [
      f.text('activity', 'What the activity is'),
      f.date('activity_date', 'When'),
      f.notes('hazards', 'What could go wrong', true),
      f.notes('controls', 'What reduces the risk', true),
      f.number('people_at_risk', 'How many people are involved'),
    ],
  },
  {
    key: 'fire_drill',
    name: 'Fire drill record',
    category: 'Health & safety',
    summary: 'A drill recorded with its evacuation time and whatever went wrong.',
    audience: 'For anybody who has to evidence drills to an inspector.',
    outcome: 'A drill is recorded with its timing and its findings.',
    respondents: 'The fire marshal.',
    ownerName: 'Health and safety',
    approvals: [{ key: 'hs_lead', name: 'Health and safety lead', byRole: 'safety_lead', dueInHours: 168 }],
    retentionDays: 3650,
    fields: [
      f.date('drill_date', 'Date'),
      f.number('evacuation_minutes', 'Minutes to evacuate'),
      f.number('people_present', 'People in the building'),
      f.notes('drill_issues', 'What went wrong', false),
    ],
  },

  // -------------------------------------------------------- Compliance
  {
    key: 'data_subject_request',
    name: 'Data subject request',
    category: 'Compliance',
    summary: 'A request for personal data logged with its legal clock running from the moment it arrives.',
    audience: 'For anybody subject to data protection law, which is everybody.',
    outcome: 'A request is answered within the statutory deadline, with proof of when it arrived.',
    respondents: 'Anybody whose data you hold.',
    ownerName: 'Data protection',
    approvals: [{ key: 'dpo', name: 'Data protection officer', byRole: 'data_protection_officer', dueInHours: 48 }],
    task: { key: 'fulfil', name: 'Find and prepare the data', byRole: 'data_protection_officer' },
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('request_kind', 'What you are asking for', ['access', 'deletion', 'correction', 'portability', 'objection']),
      // The statutory clock starts when the request is *received*, and people
      // usually email somebody first. Asking when they first asked is what
      // makes the deadline defensible rather than convenient.
      f.date('first_asked_on', 'When you first asked us'),
      f.notes('request_detail', 'What specifically', true),
      f.sensitive(
        'identity_evidence',
        'How we verified who you are',
        'Required before disclosing personal data — releasing it to the wrong person is itself a breach.',
        false,
      ),
    ],
  },
  {
    key: 'data_breach',
    name: 'Data breach report',
    category: 'Compliance',
    summary: 'A suspected breach logged immediately, because the seventy-two hours start when you find out.',
    audience: 'For anybody who would have to notify a regulator.',
    outcome: 'A breach is assessed, contained, and notified where the law requires it.',
    respondents: 'Anybody who noticed.',
    ownerName: 'Data protection',
    approvals: [{ key: 'dpo', name: 'Data protection officer', byRole: 'data_protection_officer', dueInHours: 4 }],
    task: { key: 'contain', name: 'Contain and assess', byRole: 'data_protection_officer' },
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.date('discovered_on', 'When you found out'),
      f.notes('breach_detail', 'What happened', true),
      f.choice('data_involved', 'What kind of data', ['contact', 'financial', 'health', 'identity', 'unknown']),
      f.number('people_affected', 'Roughly how many people'),
      f.yesNo('still_ongoing', 'Is it still happening?'),
    ],
  },
  {
    key: 'policy_acknowledgement',
    name: 'Policy acknowledgement',
    category: 'Compliance',
    summary: 'Confirmation that somebody read a policy, with the version they read recorded.',
    audience: 'For anybody who has to show an auditor that staff were told.',
    outcome: 'An acknowledgement is recorded against a named policy version.',
    respondents: 'Every member of staff.',
    ownerName: 'Compliance',
    approvals: [{ key: 'compliance', name: 'Compliance check', byRole: 'compliance_lead', dueInHours: 168 }],
    retentionDays: 2555,
    fields: [
      f.text('policy_name', 'Which policy'),
      f.text('policy_version', 'Version'),
      // Which version, and when it was issued — an acknowledgement that does
      // not name a dated version proves nothing to an auditor.
      f.date('policy_issued_on', 'Date on that version'),
      f.yesNo('read_and_understood', 'Have you read and understood it?'),
      f.notes('questions', 'Anything unclear', false),
    ],
  },
  {
    key: 'conflict_of_interest',
    name: 'Conflict of interest',
    category: 'Compliance',
    summary: 'An interest declared once and reviewed, rather than remembered at the wrong moment.',
    audience: 'For any board, charity or regulated organization.',
    outcome: 'An interest is declared, assessed and recorded on the register.',
    respondents: 'Any member of staff, trustee or director.',
    ownerName: 'Compliance',
    approvals: [{ key: 'compliance', name: 'Compliance review', byRole: 'compliance_lead', dueInHours: 120 }],
    retentionDays: 3650,
    fields: [
      f.choice('interest_kind', 'Kind of interest', ['financial', 'family', 'directorship', 'gift', 'other']),
      // When it arose, not when it was declared. The gap between the two is
      // the thing a register is for.
      f.date('arose_on', 'When it arose'),
      f.notes('interest_detail', 'Describe it', true),
      f.money('interest_value', 'Value, if it has one', false),
      f.yesNo('ongoing', 'Is it ongoing?'),
    ],
  },
  {
    key: 'whistleblowing',
    name: 'Whistleblowing report',
    category: 'Compliance',
    summary: 'A report routed to a small group, handled outside the normal chain, and acknowledged.',
    audience: 'For any organization with a duty to protect whistleblowers.',
    outcome: 'A report is assessed and investigated without going through the people it concerns.',
    respondents: 'Anybody.',
    ownerName: 'Audit committee',
    approvals: [{ key: 'audit', name: 'Audit committee', byRole: 'audit_committee', dueInHours: 48 }],
    task: { key: 'investigate', name: 'Investigate', byRole: 'audit_committee' },
    retentionDays: 3650,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('concern_kind', 'What this concerns', ['fraud', 'safety', 'bribery', 'conduct', 'other']),
      f.date('concern_since', 'When it started, as far as you know'),
      f.notes('concern_detail', 'What you have seen', true),
      f.sensitive(
        'people_named',
        'Who is involved',
        'Needed to route the report away from anybody it concerns. Restricted so it is visible only to the audit committee.',
        false,
      ),
      f.yesNo('anonymous_preferred', 'Would you prefer to stay anonymous?'),
    ],
  },

  // ------------------------------------------------------------ Education
  {
    key: 'school_trip',
    name: 'School trip consent',
    category: 'Education',
    summary: 'Consent, medical needs and emergency contacts collected once, with a chase for whoever has not replied.',
    audience: 'For a school or club taking children off site.',
    outcome: 'Every child on the trip has consent, medical information and a contact on file.',
    respondents: 'A parent or guardian.',
    ownerName: 'School office',
    approvals: [{ key: 'trip_lead', name: 'Trip leader', byRole: 'trip_leader', dueInHours: 120 }],
    retentionDays: 1095,
    sensitivityCeiling: 'restricted',
    fields: [
      f.person('child_name', 'Child name'),
      f.text('class_group', 'Class or group'),
      f.yesNo('consent_given', 'Do you give consent?'),
      f.person('emergency_contact', 'Emergency contact name'),
      f.phone('emergency_phone', 'Emergency contact number', true),
      f.sensitive(
        'medical_needs',
        'Medical needs and allergies',
        'Needed to keep the child safe during the trip. Held only for its duration and deleted afterwards.',
        false,
      ),
    ],
  },
  {
    key: 'course_enrolment',
    name: 'Course enrolment',
    category: 'Education',
    summary: 'An application checked against entry requirements and confirmed with a place or a reason.',
    audience: 'For a college, training provider or academy.',
    outcome: 'An applicant is enrolled or declined with the reason recorded.',
    respondents: 'A prospective student.',
    ownerName: 'Admissions',
    approvals: [{ key: 'admissions', name: 'Admissions', byRole: 'admissions_officer', dueInHours: 120 }],
    retentionDays: 2555,
    fields: [
      f.text('course_wanted', 'Which course'),
      f.date('date_of_birth', 'Date of birth'),
      f.notes('prior_learning', 'Relevant qualifications or experience', true),
      f.choice('study_mode', 'How you want to study', ['full_time', 'part_time', 'evening', 'online']),
    ],
  },
  {
    key: 'absence_report',
    name: 'Student absence',
    category: 'Education',
    summary: 'An absence reported by a parent, logged against a register, and followed up if it repeats.',
    audience: 'For a school taking absence calls on a mobile.',
    outcome: 'An absence is recorded with its reason and any follow-up.',
    respondents: 'A parent or guardian.',
    ownerName: 'School office',
    approvals: [{ key: 'office', name: 'Office check', byRole: 'office_manager', dueInHours: 24 }],
    retentionDays: 1095,
    fields: [
      f.person('student_name', 'Student name'),
      f.text('class_group', 'Class'),
      f.date('absent_from', 'Absent from'),
      f.choice('absence_reason', 'Reason', ['illness', 'medical_appointment', 'family', 'other']),
      f.notes('absence_note', 'Anything else', false),
    ],
  },

  // ------------------------------------------------------------ Community
  {
    key: 'volunteer_application',
    name: 'Volunteer application',
    category: 'Community',
    summary: 'A volunteer vetted, trained and approved by the team they will join.',
    audience: 'For a charity, church or community group.',
    outcome: 'A volunteer is approved, trained, and recorded against a role.',
    respondents: 'Somebody offering their time.',
    ownerName: 'Volunteer coordinator',
    approvals: [
      { key: 'coordinator', name: 'Volunteer coordinator', byRole: 'volunteer_coordinator', dueInHours: 120 },
      { key: 'department', name: 'Department lead', byRole: 'department_head', dueInHours: 120 },
    ],
    task: { key: 'induction', name: 'Induction and training', byRole: 'volunteer_coordinator' },
    retentionDays: 1825,
    fields: [
      f.many('interested_in', 'What you would like to help with', ['events', 'admin', 'outreach', 'teaching', 'music']),
      f.notes('availability', 'When you are free', true),
      f.notes('relevant_experience', 'Anything relevant', false),
      f.person('referee_name', 'A referee', false),
      f.email('referee_email', 'Their email', false),
    ],
  },
  {
    key: 'grant_application',
    name: 'Grant application',
    category: 'Community',
    summary: 'A funding request scored against criteria and decided by a panel, with the score kept.',
    audience: 'For a funder, trust or community foundation.',
    outcome: 'An application is scored, decided by a panel, and the applicant told either way.',
    respondents: 'An organization asking for funding.',
    ownerName: 'Grants team',
    approvals: [
      { key: 'assessment', name: 'Assessment', byRole: 'grants_officer', dueInHours: 240 },
      { key: 'panel', name: 'Grants panel', byRole: 'grants_panel', dueInHours: 480 },
    ],
    retentionDays: 3650,
    fields: [
      f.text('organisation_name', 'Your organization'),
      f.money('amount_requested', 'Amount requested'),
      f.notes('project_summary', 'What the money is for', true),
      f.number('people_reached', 'How many people it reaches'),
      f.choice('funding_area', 'Area', ['youth', 'health', 'environment', 'arts', 'community']),
    ],
  },
  {
    key: 'event_registration',
    name: 'Event registration',
    category: 'Community',
    summary: 'Registration with dietary and access needs collected once and read by whoever runs the room.',
    audience: 'For anybody running events where access matters.',
    outcome: 'A place is confirmed with the attendee’s access and dietary needs recorded.',
    respondents: 'Anybody attending.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events team', byRole: 'events_lead', dueInHours: 72 }],
    retentionDays: 365,
    sensitivityCeiling: 'restricted',
    fields: [
      f.text('event_name', 'Which event'),
      f.choice('ticket_kind', 'Ticket', ['standard', 'concession', 'speaker', 'volunteer']),
      f.many('dietary', 'Dietary needs', ['none', 'vegetarian', 'vegan', 'halal', 'gluten_free']),
      f.sensitive(
        'access_needs',
        'Access needs',
        'Needed to make the event usable — step-free routes, hearing loops, a quiet space. Deleted after the event.',
        false,
      ),
    ],
  },
  {
    key: 'room_hire',
    name: 'Room hire enquiry',
    category: 'Community',
    summary: 'An outside booking quoted, checked for clashes, and confirmed with a deposit.',
    audience: 'For a church, village hall or community centre hiring out space.',
    outcome: 'A hire is confirmed with its terms, its deposit and its access arrangements.',
    respondents: 'Somebody wanting to hire the space.',
    ownerName: 'Bookings',
    approvals: [{ key: 'bookings', name: 'Bookings', byRole: 'office_manager', dueInHours: 72 }],
    retentionDays: 1095,
    fields: [
      f.text('hire_purpose', 'What the space is for'),
      f.date('hire_date', 'Date'),
      f.time('hire_start', 'From'),
      f.time('hire_end', 'Until'),
      f.number('expected_people', 'How many people'),
      f.yesNo('alcohol_served', 'Will alcohol be served?'),
    ],
  },
  {
    key: 'membership_application',
    name: 'Membership application',
    category: 'Community',
    summary: 'A new member approved, welcomed, and set up to renew without being chased by hand.',
    audience: 'For a club, society or professional body.',
    outcome: 'A member is approved and welcomed, with their renewal date recorded.',
    respondents: 'Somebody wanting to join.',
    ownerName: 'Membership',
    approvals: [{ key: 'membership', name: 'Membership secretary', byRole: 'membership_secretary', dueInHours: 168 }],
    retentionDays: 2555,
    fields: [
      f.choice('membership_kind', 'Kind', ['individual', 'family', 'student', 'corporate', 'life']),
      f.date('joining_on', 'Start from'),
      f.notes('why_joining', 'Why you would like to join', false),
      f.yesNo('newsletter_optin', 'Would you like the newsletter?'),
    ],
  },

  // ------------------------------------------------------------ Healthcare
  {
    key: 'appointment_request',
    name: 'Appointment request',
    category: 'Healthcare',
    summary: 'A request triaged by urgency, offered a slot, and confirmed — with the clinical detail restricted.',
    audience: 'For a practice, clinic or therapy service.',
    outcome: 'A patient is offered and confirmed an appointment appropriate to their need.',
    respondents: 'A patient.',
    ownerName: 'Practice team',
    approvals: [{ key: 'triage', name: 'Clinical triage', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'book', name: 'Book the appointment', byRole: 'office_manager' },
    retentionDays: 3650,
    sensitivityCeiling: 'restricted',
    fields: [
      f.date('preferred_date', 'Preferred date'),
      f.choice('appointment_kind', 'Kind', ['routine', 'follow_up', 'urgent', 'review']),
      f.sensitive(
        'reason_for_visit',
        'Reason for the appointment',
        'Clinical information needed to triage safely. Visible only to clinicians, never in an email or a webhook.',
        true,
      ),
      f.yesNo('needs_interpreter', 'Do you need an interpreter?'),
    ],
  },
  {
    key: 'referral',
    name: 'Referral',
    category: 'Healthcare',
    summary: 'A referral made, accepted or returned, with nothing sitting unacknowledged.',
    audience: 'For anybody sending or receiving clinical referrals.',
    outcome: 'A referral is accepted or returned, and the referrer knows which.',
    respondents: 'A referring clinician.',
    ownerName: 'Referral team',
    approvals: [{ key: 'receiving', name: 'Receiving service', byRole: 'clinician', dueInHours: 120 }],
    retentionDays: 3650,
    sensitivityCeiling: 'restricted',
    fields: [
      f.text('referred_to', 'Which service'),
      f.choice('referral_urgency', 'Urgency', ['routine', 'urgent', 'two_week']),
      f.sensitive(
        'clinical_summary',
        'Clinical summary',
        'The information the receiving service needs to accept or return the referral. Restricted and never sent by email.',
        true,
      ),
    ],
  },

  // ------------------------------------------------------------ Property
  {
    key: 'tenancy_application',
    name: 'Tenancy application',
    category: 'Property',
    summary: 'An application referenced, checked and decided, with every check recorded.',
    audience: 'For a landlord, agent or housing association.',
    outcome: 'A tenancy is offered or declined with its checks recorded.',
    respondents: 'A prospective tenant.',
    ownerName: 'Lettings',
    approvals: [
      { key: 'referencing', name: 'Referencing', byRole: 'lettings_officer', dueInHours: 168 },
      { key: 'landlord', name: 'Landlord decision', byRole: 'department_head', dueInHours: 120 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('property_reference', 'Which property'),
      f.date('move_in_from', 'Move in from'),
      f.money('monthly_income', 'Monthly income'),
      f.number('household_size', 'People in the household'),
      f.yesNo('pets', 'Any pets?'),
    ],
  },
  {
    key: 'repair_report',
    name: 'Tenant repair report',
    category: 'Property',
    summary: 'A repair reported with a photo, prioritised by habitability, and closed when done.',
    audience: 'For a landlord with a legal repair deadline.',
    outcome: 'A repair is carried out within its deadline and the tenant is told.',
    respondents: 'A tenant.',
    ownerName: 'Property management',
    approvals: [{ key: 'triage', name: 'Repairs triage', byRole: 'facilities_lead', dueInHours: 24 }],
    task: { key: 'repair', name: 'Carry out the repair', byRole: 'facilities_lead' },
    retentionDays: 2555,
    fields: [
      f.text('property_reference', 'Property reference'),
      f.choice('repair_kind', 'What needs fixing', ['heating', 'plumbing', 'electrical', 'structure', 'appliance', 'other']),
      f.notes('repair_detail', 'Describe it', true),
      f.yesNo('makes_unliveable', 'Does this make the home unusable?'),
    ],
  },

  // ------------------------------------------------------------ Operations
  {
    key: 'vehicle_check',
    name: 'Vehicle check',
    category: 'Operations',
    summary: 'A daily walk-round recorded, with defects escalated rather than noted and forgotten.',
    audience: 'For anybody operating vehicles under an operator licence.',
    outcome: 'A vehicle is confirmed safe to drive, or taken off the road with the defect recorded.',
    respondents: 'The driver.',
    ownerName: 'Fleet',
    approvals: [{ key: 'fleet', name: 'Fleet check', byRole: 'fleet_manager', dueInHours: 8 }],
    retentionDays: 1825,
    fields: [
      f.text('vehicle_registration', 'Registration'),
      f.number('odometer', 'Mileage'),
      f.many('defects_found', 'Anything wrong', ['none', 'tyres', 'lights', 'brakes', 'bodywork', 'load']),
      f.yesNo('safe_to_drive', 'Is it safe to drive?'),
    ],
  },
  {
    key: 'stock_request',
    name: 'Stock request',
    category: 'Operations',
    summary: 'Stock ordered against a reorder level, approved, and received against the order.',
    audience: 'For a site that runs out of things and finds out at the worst moment.',
    outcome: 'Stock is ordered, approved and received, with the quantity recorded.',
    respondents: 'Whoever notices it is low.',
    ownerName: 'Operations',
    approvals: [{ key: 'ops', name: 'Operations', byRole: 'office_manager', dueInHours: 48 }],
    task: { key: 'order', name: 'Place the order', byRole: 'procurement_lead' },
    retentionDays: 1095,
    fields: [
      f.text('item_name', 'What is needed'),
      f.number('quantity', 'How many'),
      f.choice('needed_by_when', 'When', ['today', 'this_week', 'this_month']),
      f.text('current_supplier', 'Usual supplier', false),
    ],
  },
  {
    key: 'shift_swap',
    name: 'Shift swap',
    category: 'Operations',
    summary: 'A swap agreed by both people and approved by whoever owns the rota.',
    audience: 'For anybody running a rota in a group chat.',
    outcome: 'A swap is agreed by both sides and reflected on the rota.',
    respondents: 'Anybody on a rota.',
    ownerName: 'Operations',
    approvals: [{ key: 'rota_owner', name: 'Rota owner', byRole: 'office_manager', dueInHours: 24 }],
    retentionDays: 730,
    fields: [
      f.date('shift_date', 'Which shift'),
      f.person('swapping_with', 'Swapping with'),
      f.email('swapping_with_email', 'Their email'),
      f.yesNo('they_agreed', 'Have they agreed?'),
      f.notes('swap_reason', 'Why', false),
    ],
  },
  {
    key: 'quality_issue',
    name: 'Quality issue',
    category: 'Operations',
    summary: 'A defect logged against a batch, with containment before root cause.',
    audience: 'For anybody making or handling physical product.',
    outcome: 'A defect is contained, investigated and closed with a cause.',
    respondents: 'Anybody who found it.',
    ownerName: 'Quality',
    approvals: [{ key: 'quality', name: 'Quality lead', byRole: 'quality_lead', dueInHours: 24 }],
    task: { key: 'root_cause', name: 'Root cause and fix', byRole: 'quality_lead' },
    retentionDays: 2555,
    fields: [
      f.text('batch_reference', 'Batch or lot'),
      f.notes('defect_detail', 'What is wrong', true),
      f.number('units_affected', 'How many units'),
      f.yesNo('shipped_already', 'Has any of it shipped?'),
    ],
  },
  {
    key: 'project_intake',
    name: 'Project intake',
    category: 'Operations',
    summary: 'A request for work sized and prioritised before anybody starts on it.',
    audience: 'For a team whose work arrives by tap on the shoulder.',
    outcome: 'A piece of work is accepted with a sponsor, a size and a priority — or declined.',
    respondents: 'Anybody wanting work done.',
    ownerName: 'Delivery',
    approvals: [
      { key: 'triage', name: 'Triage', byRole: 'delivery_lead', dueInHours: 72 },
      { key: 'sponsor', name: 'Sponsor', byRole: 'department_head', dueInHours: 120 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('project_name', 'What you want done'),
      f.notes('problem_statement', 'What problem it solves', true),
      f.choice('project_size', 'Rough size', ['days', 'weeks', 'months']),
      f.date('needed_by', 'Needed by', false),
      f.text('sponsor_name', 'Who is sponsoring it'),
    ],
  },
  {
    key: 'press_enquiry',
    name: 'Press enquiry',
    category: 'Communications',
    summary: 'A journalist’s question routed to somebody authorised to answer, against a deadline.',
    audience: 'For anybody who has been quoted badly because nobody replied.',
    outcome: 'An enquiry is answered by somebody authorised, before the deadline.',
    respondents: 'A journalist.',
    ownerName: 'Communications',
    approvals: [
      { key: 'comms', name: 'Communications', byRole: 'comms_lead', dueInHours: 8 },
      { key: 'spokesperson', name: 'Spokesperson', byRole: 'department_head', dueInHours: 12 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('publication', 'Publication'),
      f.notes('enquiry_detail', 'What you are asking', true),
      f.date('deadline_date', 'Your deadline'),
      f.time('deadline_time', 'Time'),
    ],
  },
  {
    key: 'speaker_request',
    name: 'Speaker request',
    category: 'Communications',
    summary: 'A request for somebody to speak, assessed for fit and availability and answered.',
    audience: 'For an organization whose leaders get asked to speak.',
    outcome: 'A speaking request is accepted or declined, with a reason.',
    respondents: 'An event organizer.',
    ownerName: 'Communications',
    approvals: [{ key: 'comms', name: 'Communications', byRole: 'comms_lead', dueInHours: 120 }],
    retentionDays: 1095,
    fields: [
      f.text('event_name', 'Event'),
      f.date('event_date', 'Date'),
      f.text('event_location', 'Where'),
      f.number('audience_size', 'Audience size'),
      f.notes('topic_wanted', 'What you would like covered', true),
      f.yesNo('fee_offered', 'Is a fee offered?'),
    ],
  },

  // ------------------------------------------------------------- Church
  {
    key: 'wedding_enquiry',
    name: 'Wedding enquiry',
    category: 'Church',
    summary: 'A couple’s enquiry checked for eligibility and dates, then booked with the minister and the building.',
    audience: 'For a church that takes wedding enquiries by phone and loses them.',
    outcome: 'A wedding is booked with a date, a minister and the legal preliminaries started.',
    respondents: 'A couple planning to marry.',
    ownerName: 'Church office',
    approvals: [
      { key: 'minister', name: 'Minister', byRole: 'minister', dueInHours: 168 },
      { key: 'bookings', name: 'Building and diary', byRole: 'office_manager', dueInHours: 120 },
    ],
    retentionDays: 3650,
    fields: [
      f.person('partner_name', 'Your partner’s name'),
      f.date('preferred_date', 'Date you have in mind'),
      f.choice('connection', 'Your connection to this church', ['member', 'attend', 'family_member', 'resident', 'none']),
      f.yesNo('either_married_before', 'Has either of you been married before?'),
      f.number('expected_guests', 'Roughly how many guests'),
      f.notes('wedding_notes', 'Anything else we should know', false),
    ],
  },
  {
    key: 'funeral_arrangement',
    name: 'Funeral arrangement',
    category: 'Church',
    summary: 'An arrangement handled quickly and gently, with the minister, the building and the family kept in step.',
    audience: 'For a church supporting families at short notice.',
    outcome: 'A service is arranged with a minister, a time and the family’s wishes recorded.',
    respondents: 'A family member or funeral director.',
    ownerName: 'Church office',
    approvals: [{ key: 'minister', name: 'Minister', byRole: 'minister', dueInHours: 24 }],
    task: { key: 'arrange', name: 'Arrange the service', byRole: 'office_manager' },
    retentionDays: 3650,
    sensitivityCeiling: 'restricted',
    fields: [
      f.person('deceased_name', 'Name of the person who has died'),
      f.date('service_date', 'Date you hope for'),
      f.choice('service_kind', 'Kind of service', ['church', 'crematorium', 'graveside', 'memorial']),
      f.text('funeral_director', 'Funeral director', false),
      f.sensitive(
        'family_wishes',
        'The family’s wishes',
        'Held so the service reflects what the family asked for. Visible to the minister and the office only, and never sent by email.',
        false,
      ),
    ],
  },
  {
    key: 'baptism_request',
    name: 'Baptism or dedication request',
    category: 'Church',
    summary: 'A request recorded, prepared for, and entered in the register afterwards.',
    audience: 'For a church keeping baptism records in a paper book.',
    outcome: 'A baptism is prepared for, carried out, and entered in the register.',
    respondents: 'A parent, guardian or candidate.',
    ownerName: 'Church office',
    approvals: [{ key: 'minister', name: 'Minister', byRole: 'minister', dueInHours: 168 }],
    task: { key: 'prepare', name: 'Preparation session', byRole: 'minister' },
    retentionDays: null,
    fields: [
      f.person('candidate_name', 'Who is being baptised'),
      f.date('candidate_dob', 'Date of birth'),
      f.choice('rite_kind', 'Which', ['infant_baptism', 'believer_baptism', 'dedication', 'confirmation']),
      f.date('hoped_date', 'Date you hope for'),
      f.notes('godparents', 'Godparents or sponsors', false),
    ],
  },
  {
    key: 'pastoral_care',
    name: 'Pastoral care request',
    category: 'Church',
    summary: 'A request for support routed to a small named team, with the detail kept out of every email.',
    audience: 'For a church where requests reach whoever happens to answer.',
    outcome: 'Somebody is visited or contacted by the right person, and the contact is recorded.',
    respondents: 'Anybody, for themselves or somebody else.',
    ownerName: 'Pastoral team',
    approvals: [{ key: 'pastoral_lead', name: 'Pastoral lead', byRole: 'pastoral_lead', dueInHours: 24 }],
    task: { key: 'visit', name: 'Make contact', byRole: 'pastoral_lead' },
    retentionDays: 1825,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('care_kind', 'What is needed', ['visit', 'call', 'prayer', 'practical_help', 'bereavement']),
      f.choice('urgency', 'How soon', ['today', 'this_week', 'whenever']),
      f.sensitive(
        'situation',
        'What is happening',
        'Personal circumstances shared in confidence. Restricted so it reaches only the pastoral team, and never an email body.',
        true,
      ),
      f.yesNo('for_someone_else', 'Is this about somebody else?'),
    ],
  },
  {
    key: 'prayer_request',
    name: 'Prayer request',
    category: 'Church',
    summary: 'A request handled with the confidential ones kept off the public list.',
    audience: 'For a church whose prayer list is a group email.',
    outcome: 'A request reaches those who will pray, at the level of privacy the person asked for.',
    respondents: 'Anybody.',
    ownerName: 'Prayer team',
    approvals: [{ key: 'prayer_lead', name: 'Prayer team lead', byRole: 'prayer_lead', dueInHours: 24 }],
    retentionDays: 365,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('share_with', 'Who may see this', ['prayer_team_only', 'whole_church', 'leaders_only']),
      f.sensitive(
        'request_detail',
        'What to pray for',
        'Often health or family circumstances. Restricted so the sharing choice above is enforced rather than trusted.',
        true,
      ),
      f.yesNo('ongoing_request', 'Is this ongoing?'),
    ],
  },
  {
    key: 'benevolence_request',
    name: 'Hardship fund request',
    category: 'Church',
    summary: 'A request for financial help assessed by two people, with the decision and the amount recorded.',
    audience: 'For a church or charity with a benevolence fund and no process around it.',
    outcome: 'Help is given or declined by a panel, with the reason and the amount on record.',
    respondents: 'Somebody in need, or a leader on their behalf.',
    ownerName: 'Benevolence panel',
    approvals: [
      { key: 'pastoral', name: 'Pastoral assessment', byRole: 'pastoral_lead', dueInHours: 72 },
      { key: 'treasurer', name: 'Treasurer', byRole: 'treasurer', dueInHours: 120 },
    ],
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.money('amount_needed', 'Amount needed'),
      f.choice('help_kind', 'What it is for', ['food', 'utilities', 'rent', 'travel', 'medical', 'other']),
      f.sensitive(
        'circumstances',
        'Your circumstances',
        'Needed to assess the request fairly. Restricted so it is seen only by the two people deciding.',
        true,
      ),
      f.yesNo('asked_before', 'Have you asked before?'),
    ],
  },
  {
    key: 'ministry_application',
    name: 'Ministry team application',
    category: 'Church',
    summary: 'Somebody joining a team, with the safeguarding check and references before they start.',
    audience: 'For a church placing volunteers with children, youth or vulnerable adults.',
    outcome: 'A volunteer is placed on a team with their checks complete and recorded.',
    respondents: 'Somebody wanting to serve.',
    ownerName: 'Volunteer coordinator',
    approvals: [
      { key: 'team_lead', name: 'Team leader', byRole: 'department_head', dueInHours: 120 },
      { key: 'safeguarding', name: 'Safeguarding check', byRole: 'safeguarding_lead', dueInHours: 168 },
    ],
    task: { key: 'induct', name: 'Induction and training', byRole: 'volunteer_coordinator' },
    retentionDays: 1825,
    sensitivityCeiling: 'restricted',
    fields: [
      f.many('team_wanted', 'Which team', ['children', 'youth', 'worship', 'welcome', 'tech', 'catering', 'prayer']),
      f.notes('experience', 'Relevant experience', false),
      f.yesNo('works_with_children', 'Would this involve children or vulnerable adults?'),
      f.sensitive(
        'check_reference',
        'Existing check reference, if you have one',
        'Recorded as a reference so no certificate is stored. Needed to confirm the check is current before placement.',
        false,
      ),
      f.person('church_referee', 'Somebody who knows you here', false),
    ],
  },
  {
    key: 'small_group_signup',
    name: 'Small group signup',
    category: 'Church',
    summary: 'Somebody placed in a group that actually has room, with the leader told.',
    audience: 'For a church running groups off a spreadsheet.',
    outcome: 'Somebody is placed in a group and the leader knows to expect them.',
    respondents: 'Anybody wanting to join a group.',
    ownerName: 'Groups coordinator',
    approvals: [{ key: 'groups', name: 'Groups coordinator', byRole: 'groups_coordinator', dueInHours: 120 }],
    retentionDays: 1095,
    fields: [
      f.choice('preferred_day', 'Which evening suits', ['monday', 'tuesday', 'wednesday', 'thursday', 'sunday']),
      f.choice('group_kind', 'What kind', ['bible_study', 'prayer', 'newcomers', 'parents', 'young_adults', 'seniors']),
      f.yesNo('needs_childcare', 'Do you need childcare?'),
      f.yesNo('needs_transport', 'Do you need a lift?'),
    ],
  },
  {
    key: 'mission_trip',
    name: 'Mission trip application',
    category: 'Church',
    summary: 'An application with references, medical needs and safeguarding handled before travel is booked.',
    audience: 'For a church or charity sending teams overseas.',
    outcome: 'A participant is approved, checked and prepared before anything is booked.',
    respondents: 'Somebody applying to go.',
    ownerName: 'Missions team',
    approvals: [
      { key: 'trip_lead', name: 'Trip leader', byRole: 'trip_leader', dueInHours: 168 },
      { key: 'safeguarding', name: 'Safeguarding and insurance', byRole: 'safeguarding_lead', dueInHours: 168 },
    ],
    task: { key: 'prepare', name: 'Training and preparation', byRole: 'trip_leader' },
    retentionDays: 1825,
    sensitivityCeiling: 'restricted',
    fields: [
      f.text('destination', 'Which trip'),
      f.date('travel_from', 'Travel dates from'),
      f.sensitive(
        'medical_and_dietary',
        'Medical needs, medication and allergies',
        'Needed for travel insurance and to keep somebody safe abroad, where medical help may be far away. Deleted after the trip.',
        true,
      ),
      f.yesNo('passport_valid', 'Is your passport valid for six months past the return?'),
      f.person('emergency_contact', 'Emergency contact'),
      f.phone('emergency_phone', 'Their number', true),
    ],
  },
  {
    key: 'giving_pledge',
    name: 'Giving or pledge commitment',
    category: 'Church',
    summary: 'A commitment recorded and acknowledged, with the amounts seen only by the treasurer.',
    audience: 'For a church running a giving campaign.',
    outcome: 'A pledge is recorded, acknowledged, and visible only to those who must see it.',
    respondents: 'A member or regular giver.',
    ownerName: 'Treasurer',
    approvals: [{ key: 'treasurer', name: 'Treasurer', byRole: 'treasurer', dueInHours: 168 }],
    retentionDays: 2555,
    sensitivityCeiling: 'restricted',
    fields: [
      f.choice('pledge_frequency', 'How often', ['one_off', 'monthly', 'quarterly', 'annually']),
      f.sensitive(
        'pledge_amount',
        'Amount',
        'What somebody gives is among the most sensitive things a church holds. Restricted so it reaches the treasurer and nobody else.',
        true,
      ),
      f.date('starting_from', 'Starting from'),
      f.yesNo('gift_aid', 'Are you a taxpayer who can gift aid this?'),
    ],
  },

  // ------------------------------------------------------------ Projects
  {
    key: 'project_charter',
    name: 'Project charter',
    category: 'Projects',
    summary: 'A project defined, sponsored and approved before anybody is assigned to it.',
    audience: 'For a delivery team where projects start without anybody agreeing what they are.',
    outcome: 'A project is approved with a sponsor, a scope, a budget and a first milestone.',
    respondents: 'Whoever wants the project to happen.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'sponsor', name: 'Sponsor', byRole: 'department_head', dueInHours: 168 },
      { key: 'portfolio', name: 'Portfolio board', byRole: 'portfolio_board', dueInHours: 240 },
    ],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Project name'),
      f.notes('objective', 'What it will achieve', true),
      f.notes('out_of_scope', 'What it will deliberately not do', true),
      f.money('budget', 'Budget'),
      f.date('target_end', 'Target completion'),
      f.text('sponsor_name', 'Sponsor'),
    ],
  },
  {
    key: 'scope_change',
    name: 'Scope change request',
    category: 'Projects',
    summary: 'A change to what was agreed, costed and approved by whoever is paying for it.',
    audience: 'For any project that has quietly grown by a third.',
    outcome: 'A scope change is approved with its cost and schedule impact recorded, or declined.',
    respondents: 'Anybody on or around the project.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'project_manager', name: 'Project manager', byRole: 'delivery_lead', dueInHours: 72 },
      { key: 'sponsor', name: 'Sponsor', byRole: 'department_head', dueInHours: 120 },
    ],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.notes('change_wanted', 'What should change', true),
      f.notes('why_now', 'Why it is needed now', true),
      f.money('cost_impact', 'Cost impact', false),
      f.number('days_impact', 'Days added to the schedule'),
      f.choice('change_priority', 'Priority', ['must_have', 'should_have', 'nice_to_have']),
    ],
  },
  {
    key: 'project_risk',
    name: 'Project risk',
    category: 'Projects',
    summary: 'A risk raised with an owner and a mitigation, rather than a colour on a slide.',
    audience: 'For a project whose risk log is only updated before a steering meeting.',
    outcome: 'A risk has a named owner, a mitigation and a review date.',
    respondents: 'Anybody on the project.',
    ownerName: 'Portfolio office',
    approvals: [{ key: 'project_manager', name: 'Project manager', byRole: 'delivery_lead', dueInHours: 72 }],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.notes('risk_detail', 'What might go wrong', true),
      f.choice('likelihood', 'How likely', ['low', 'medium', 'high']),
      f.choice('risk_impact', 'How bad if it happens', ['low', 'medium', 'high', 'severe']),
      f.notes('mitigation', 'What would reduce it', true),
      f.person('risk_owner', 'Who owns it'),
    ],
  },
  {
    key: 'issue_escalation',
    name: 'Issue escalation',
    category: 'Projects',
    summary: 'A blocker escalated with a deadline on the answer, not just a flag on a report.',
    audience: 'For a team whose blockers sit in a status column for weeks.',
    outcome: 'A blocker reaches somebody who can clear it, and is answered within a deadline.',
    respondents: 'Anybody who is blocked.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'project_manager', name: 'Project manager', byRole: 'delivery_lead', dueInHours: 24 },
      { key: 'sponsor', name: 'Sponsor decision', byRole: 'department_head', dueInHours: 72 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('project_name', 'Which project'),
      f.notes('blocked_by', 'What is blocking you', true),
      f.number('days_blocked', 'Days blocked so far'),
      f.choice('escalation_impact', 'What it affects', ['a_task', 'a_milestone', 'the_whole_project']),
      f.notes('decision_needed', 'What decision would unblock it', true),
    ],
  },
  {
    key: 'milestone_signoff',
    name: 'Milestone sign-off',
    category: 'Projects',
    summary: 'A milestone accepted by whoever asked for it, with the evidence attached.',
    audience: 'For a team that hears "that is not what we wanted" at the end.',
    outcome: 'A milestone is formally accepted, or sent back with what is missing.',
    respondents: 'The delivery team.',
    ownerName: 'Portfolio office',
    approvals: [{ key: 'sponsor', name: 'Sponsor acceptance', byRole: 'department_head', dueInHours: 120 }],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.text('milestone_name', 'Which milestone'),
      f.date('completed_on', 'Completed on'),
      f.notes('what_was_delivered', 'What was delivered', true),
      f.url('evidence_link', 'Where the evidence is', false),
    ],
  },
  {
    key: 'resource_request',
    name: 'Resource request',
    category: 'Projects',
    summary: 'People asked for by name or skill, with the releasing manager agreeing in writing.',
    audience: 'For a matrix organization where people are promised twice.',
    outcome: 'A person is assigned to a project with their manager’s agreement recorded.',
    respondents: 'A project manager.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'releasing_manager', name: 'Their manager', byRole: 'line_manager', dueInHours: 96 },
      { key: 'portfolio', name: 'Portfolio office', byRole: 'portfolio_board', dueInHours: 120 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('project_name', 'Which project'),
      f.text('skill_needed', 'Skill or person needed'),
      f.number('days_needed', 'Days needed'),
      f.date('needed_from', 'From'),
      f.notes('why_this_person', 'Why this person or skill', true),
    ],
  },
  {
    key: 'stage_gate',
    name: 'Stage gate review',
    category: 'Projects',
    summary: 'A decision to continue, change or stop — taken deliberately rather than by drift.',
    audience: 'For a portfolio where projects are never actually stopped.',
    outcome: 'A project is continued, replanned or stopped, with the reason recorded.',
    respondents: 'The project manager.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'portfolio', name: 'Portfolio board', byRole: 'portfolio_board', dueInHours: 240 },
      { key: 'finance', name: 'Finance', byRole: 'finance_reviewer', dueInHours: 168 },
    ],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.choice('gate', 'Which gate', ['initiation', 'design', 'build', 'launch', 'closure']),
      f.notes('progress_summary', 'Where it actually is', true),
      f.money('spent_so_far', 'Spent so far'),
      f.money('forecast_remaining', 'Forecast to complete'),
      f.choice('recommendation', 'Recommendation', ['continue', 'replan', 'pause', 'stop']),
    ],
  },
  {
    key: 'lessons_learned',
    name: 'Lessons learned',
    category: 'Projects',
    summary: 'What was learned captured while it is fresh, and routed to whoever can change the practice.',
    audience: 'For an organization that runs the same retrospective every project.',
    outcome: 'A lesson is recorded, owned, and turned into a change somebody made.',
    respondents: 'Anybody on the project.',
    ownerName: 'Portfolio office',
    approvals: [{ key: 'portfolio', name: 'Portfolio office', byRole: 'portfolio_board', dueInHours: 240 }],
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.choice('lesson_area', 'Area', ['planning', 'people', 'suppliers', 'technical', 'communication']),
      f.notes('what_happened', 'What happened', true),
      f.notes('do_differently', 'What we should do differently', true),
      f.yesNo('would_repeat', 'Would you run it the same way again?'),
    ],
  },
  {
    key: 'status_report',
    name: 'Status report',
    category: 'Projects',
    summary: 'A report submitted on a rhythm, chased when it is late, and readable in one screen.',
    audience: 'For a portfolio office chasing reports by email every Friday.',
    outcome: 'A current report exists for every live project, and a late one is chased automatically.',
    respondents: 'A project manager.',
    ownerName: 'Portfolio office',
    approvals: [{ key: 'portfolio', name: 'Portfolio office', byRole: 'portfolio_board', dueInHours: 48 }],
    retentionDays: 1825,
    fields: [
      f.text('project_name', 'Which project'),
      f.choice('overall_status', 'Overall', ['on_track', 'at_risk', 'off_track', 'on_hold']),
      f.notes('done_this_period', 'Done since last time', true),
      f.notes('next_period', 'Planned for next', true),
      f.notes('help_needed', 'Where you need help', false),
      f.number('percent_complete', 'Roughly what percent complete'),
    ],
  },
  {
    key: 'project_closure',
    name: 'Project closure',
    category: 'Projects',
    summary: 'A project formally closed, with its budget released and its handover accepted.',
    audience: 'For an organization whose finished projects still hold budget and people.',
    outcome: 'A project is closed, handed over, and its remaining budget released.',
    respondents: 'The project manager.',
    ownerName: 'Portfolio office',
    approvals: [
      { key: 'sponsor', name: 'Sponsor', byRole: 'department_head', dueInHours: 168 },
      { key: 'finance', name: 'Finance closure', byRole: 'finance_reviewer', dueInHours: 168 },
    ],
    task: { key: 'handover', name: 'Handover to the team who will run it', byRole: 'delivery_lead' },
    retentionDays: 3650,
    fields: [
      f.text('project_name', 'Which project'),
      f.date('closed_on', 'Closing on'),
      f.yesNo('objectives_met', 'Were the objectives met?'),
      f.money('final_spend', 'Final spend'),
      f.text('handover_to', 'Who takes it on'),
      f.notes('outstanding', 'Anything still outstanding', false),
    ],
  },

  // -------------------------------------------------------------- Events
  {
    key: 'event_proposal',
    name: 'Event proposal',
    category: 'Events',
    summary: 'An event costed and approved before a date is announced or a deposit paid.',
    audience: 'For anybody who has announced an event and then found the room was booked.',
    outcome: 'An event is approved with a budget, a date and an owner.',
    respondents: 'Whoever wants to run the event.',
    ownerName: 'Events team',
    approvals: [
      { key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 120 },
      { key: 'finance', name: 'Budget approval', byRole: 'finance_reviewer', dueInHours: 168 },
    ],
    retentionDays: 1825,
    fields: [
      f.text('event_name', 'What the event is'),
      f.date('event_date', 'Proposed date'),
      f.number('expected_attendance', 'Expected attendance'),
      f.money('event_budget', 'Budget needed'),
      f.notes('event_purpose', 'Why we are doing it', true),
      f.choice('event_audience', 'Who it is for', ['public', 'members', 'staff', 'invited_guests']),
    ],
  },
  {
    key: 'venue_sourcing',
    name: 'Venue sourcing',
    category: 'Events',
    summary: 'Venues compared on cost, capacity and access before one is held.',
    audience: 'For anybody who booked a venue and discovered it had steps.',
    outcome: 'A venue is chosen and held, with its access and cost recorded.',
    respondents: 'Whoever is organising.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 120 }],
    task: { key: 'hold_venue', name: 'Hold the venue', byRole: 'events_lead' },
    retentionDays: 1095,
    fields: [
      f.text('event_name', 'Which event'),
      f.date('event_date', 'Date'),
      f.number('capacity_needed', 'Capacity needed'),
      f.money('venue_budget', 'Budget'),
      f.yesNo('step_free_required', 'Is step-free access required?'),
      f.notes('venue_options', 'Venues you have looked at', false),
    ],
  },
  {
    key: 'speaker_invitation',
    name: 'Speaker invitation',
    category: 'Events',
    summary: 'An invitation sent, chased and confirmed, with the fee and travel agreed in writing.',
    audience: 'For an event team confirming speakers over direct messages.',
    outcome: 'A speaker is confirmed with their fee, travel and requirements agreed.',
    respondents: 'The event organiser.',
    ownerName: 'Events team',
    approvals: [
      { key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 72 },
      { key: 'finance', name: 'Fee approval', byRole: 'finance_reviewer', dueInHours: 120 },
    ],
    task: { key: 'confirm', name: 'Confirm with the speaker', byRole: 'events_lead' },
    retentionDays: 1825,
    fields: [
      f.text('event_name', 'Which event'),
      f.person('speaker_name', 'Speaker'),
      f.email('speaker_email', 'Their email'),
      f.money('speaker_fee', 'Fee offered', false),
      f.notes('talk_topic', 'What you would like them to cover', true),
      f.yesNo('travel_needed', 'Does travel need arranging?'),
    ],
  },
  {
    key: 'sponsorship_application',
    name: 'Sponsorship application',
    category: 'Events',
    summary: 'A sponsor assessed for fit as well as money, with the package agreed before anything is printed.',
    audience: 'For an event that has had to remove a logo after printing.',
    outcome: 'A sponsorship is accepted with its package and its conditions recorded.',
    respondents: 'A prospective sponsor.',
    ownerName: 'Events team',
    approvals: [
      { key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 120 },
      { key: 'comms', name: 'Brand and ethics check', byRole: 'comms_lead', dueInHours: 120 },
    ],
    retentionDays: 2555,
    fields: [
      f.text('sponsor_organisation', 'Your organization'),
      f.choice('package_wanted', 'Package', ['headline', 'gold', 'silver', 'stand_only', 'in_kind']),
      f.money('sponsorship_amount', 'Amount offered'),
      f.notes('what_you_do', 'What your organization does', true),
      f.url('sponsor_website', 'Website', false),
    ],
  },
  {
    key: 'event_supplier',
    name: 'Event supplier booking',
    category: 'Events',
    summary: 'A supplier booked with their insurance and arrival time confirmed before the day.',
    audience: 'For anybody who has had a supplier arrive without public liability cover.',
    outcome: 'A supplier is booked, insured, and expected at a known time.',
    respondents: 'The event organiser.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 96 }],
    retentionDays: 2555,
    fields: [
      f.text('event_name', 'Which event'),
      f.text('supplier_name', 'Supplier'),
      f.choice('supplier_kind', 'What they provide', ['catering', 'av', 'staging', 'security', 'photography', 'other']),
      f.money('supplier_cost', 'Cost'),
      f.time('arrival_time', 'Arrival time'),
      f.yesNo('insurance_confirmed', 'Have you seen their public liability cover?'),
    ],
  },
  {
    key: 'event_volunteer',
    name: 'Event volunteer signup',
    category: 'Events',
    summary: 'Shifts signed up for, confirmed, and reminded the day before.',
    audience: 'For an event run by volunteers from a spreadsheet.',
    outcome: 'Every shift has a named person who has been reminded.',
    respondents: 'A volunteer.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Volunteer coordinator', byRole: 'volunteer_coordinator', dueInHours: 72 }],
    retentionDays: 365,
    fields: [
      f.text('event_name', 'Which event'),
      f.many('shifts_wanted', 'Which shifts', ['setup', 'morning', 'afternoon', 'evening', 'pack_down']),
      f.many('roles_happy_with', 'What you are happy to do', ['welcome', 'registration', 'stewarding', 'catering', 'tech']),
      f.yesNo('done_before', 'Have you volunteered with us before?'),
      f.phone('volunteer_phone', 'Number for the day', true),
    ],
  },
  {
    key: 'ticket_change',
    name: 'Ticket refund or transfer',
    category: 'Events',
    summary: 'A refund or name change assessed against the terms, and answered before the event.',
    audience: 'For anybody handling ticket changes in a shared inbox.',
    outcome: 'A ticket is refunded, transferred or declined, before the event happens.',
    respondents: 'A ticket holder.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events team', byRole: 'events_lead', dueInHours: 48 }],
    retentionDays: 1095,
    fields: [
      f.text('event_name', 'Which event'),
      f.text('booking_reference', 'Booking reference'),
      f.choice('change_wanted', 'What you need', ['refund', 'transfer_to_someone', 'change_date', 'cancel']),
      f.person('transfer_to', 'Transfer to', false),
      f.notes('change_reason', 'Reason', false),
    ],
  },
  {
    key: 'catering_order',
    name: 'Catering order',
    category: 'Events',
    summary: 'Numbers and dietary requirements confirmed by a deadline, not guessed on the day.',
    audience: 'For anybody who has ordered forty lunches for sixty people.',
    outcome: 'Catering is ordered against confirmed numbers and requirements.',
    respondents: 'The event organiser.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 72 }],
    retentionDays: 730,
    fields: [
      f.text('event_name', 'Which event'),
      f.date('catering_date', 'Date'),
      f.number('headcount', 'How many people'),
      f.choice('service_kind', 'What kind', ['tea_coffee', 'sandwich_lunch', 'hot_buffet', 'seated_meal', 'canapes']),
      f.notes('dietary_summary', 'Dietary requirements to cover', true),
      f.money('catering_budget', 'Budget per head', false),
    ],
  },
  {
    key: 'av_request',
    name: 'Audio-visual request',
    category: 'Events',
    summary: 'What is needed in the room agreed with the tech team before the day, including a rehearsal.',
    audience: 'For anybody who has spent the first ten minutes fixing a microphone.',
    outcome: 'The technical needs are agreed, set up, and rehearsed before doors open.',
    respondents: 'The event organiser or a speaker.',
    ownerName: 'Technical team',
    approvals: [{ key: 'tech', name: 'Technical lead', byRole: 'tech_lead', dueInHours: 96 }],
    task: { key: 'setup', name: 'Set up and rehearse', byRole: 'tech_lead' },
    retentionDays: 365,
    fields: [
      f.text('event_name', 'Which event'),
      f.date('event_date', 'Date'),
      f.many('av_needed', 'What is needed', ['projector', 'microphones', 'stage_lighting', 'live_stream', 'recording', 'hearing_loop']),
      f.number('speakers_count', 'How many speakers'),
      f.yesNo('rehearsal_wanted', 'Do you want a rehearsal?'),
    ],
  },
  {
    key: 'event_debrief',
    name: 'Event debrief',
    category: 'Events',
    summary: 'What worked and what did not, captured within a week while anybody still remembers.',
    audience: 'For a team that runs the same event every year and repeats the same problems.',
    outcome: 'A debrief is recorded and its actions owned before the next event is planned.',
    respondents: 'Anybody who worked on it.',
    ownerName: 'Events team',
    approvals: [{ key: 'events', name: 'Events lead', byRole: 'events_lead', dueInHours: 168 }],
    retentionDays: 1825,
    fields: [
      f.text('event_name', 'Which event'),
      f.number('actual_attendance', 'How many actually came'),
      f.rating('how_it_went', 'How it went overall'),
      f.notes('what_worked', 'What worked', true),
      f.notes('what_to_change', 'What to change next time', true),
      f.money('actual_spend', 'What it actually cost', false),
    ],
  },
];
