/** Additional purpose-built packs for categories that had fewer than five choices. */
import type { PackField, PackSpec } from './generate.js';
import { when } from './spec-helpers.js';

const f = {
  text: (key: string, label: string, required = true): PackField => ({ key, label, type: 'short_text', required, classification: 'internal' }),
  person: (key: string, label: string, required = true): PackField => ({ key, label, type: 'short_text', required, classification: 'confidential' }),
  email: (key: string, label: string, required = true): PackField => ({ key, label, type: 'email', required, classification: 'confidential' }),
  phone: (key: string, label: string, required = false): PackField => ({ key, label, type: 'phone', required, classification: 'confidential' }),
  notes: (key: string, label: string, required = true): PackField => ({ key, label, type: 'long_text', required, classification: 'confidential' }),
  date: (key: string, label: string, required = true): PackField => ({ key, label, type: 'date', required, classification: 'internal' }),
  money: (key: string, label: string, required = true): PackField => ({ key, label, type: 'currency', required, classification: 'confidential' }),
  choice: (key: string, label: string, choices: string[], required = true): PackField => ({ key, label, type: 'dropdown', choices, required, classification: 'internal' }),
  yesNo: (key: string, label: string, required = true): PackField => ({ key, label, type: 'yes_no', required, classification: 'internal' }),
  private: (key: string, label: string, reason: string, required = false): PackField => ({ key, label, type: 'long_text', required, classification: 'restricted', reason }),
  recorded: (key: string, label: string): PackField => ({ key, label, type: 'short_text', required: false, classification: 'internal', setBy: 'operator', help: 'The assigned team records this after completing the work.' }),
  number: (key: string, label: string, required = true): PackField => ({ key, label, type: 'number', required, classification: 'internal' }),
  time: (key: string, label: string, required = false): PackField => ({ key, label, type: 'time', required, classification: 'internal' }),
  url: (key: string, label: string, required = false): PackField => ({ key, label, type: 'url', required, classification: 'internal' }),
  many: (key: string, label: string, choices: string[], required = false): PackField => ({ key, label, type: 'multi_choice', choices, required, classification: 'internal' }),
};

export const EXTRA_PACKS: PackSpec[] = [
  // Communications
  {
    key: 'content_approval', name: 'Content approval', category: 'Communications',
    summary: 'A public message taken with where it goes, when, who it names and whose consent it needs, checked for accuracy, consent and timing before release.',
    audience: 'For teams publishing news, campaigns or social posts.', outcome: 'The approved version is published with a release reference.',
    respondents: 'The person requesting publication.', ownerName: 'Communications',
    approvals: [{ key: 'editor', name: 'Editorial review', byRole: 'comms_lead', dueInHours: 8 }, { key: 'owner', name: 'Subject owner', byRole: 'department_head', dueInHours: 8 }],
    task: { key: 'publish_content', name: 'Publish the approved version', byRole: 'process_owner', description: 'Check the final version, permissions and scheduled channel; publish only the approved copy and record its link.', requiredFields: ['published_link_reference'] },
    completionMessage: 'The approved content has been published and its link recorded.', retentionDays: 1095,
    groups: {
      'The piece': {},
      'The copy': {},
      'People in it': { description: 'Anyone named, quoted or pictured needs to have agreed.', visibleWhen: when.yes('people_identifiable') },
      'Timing': {},
    },
    fields: [
      { ...f.choice('channel', 'Where will it appear?', ['website', 'email', 'social', 'press', 'print', 'internal']), group: 'The piece' },
      { ...f.many('social_networks', 'Which networks', ['linkedin', 'x', 'instagram', 'facebook', 'tiktok', 'youtube']), group: 'The piece', requiredWhen: when.is('channel', 'social') },
      { ...f.text('headline', 'Headline or working title'), group: 'The piece' },
      { ...f.choice('content_kind', 'What kind of piece', ['news', 'campaign', 'event_promotion', 'statement', 'recruitment', 'other']), group: 'The piece' },
      { ...f.notes('message', 'What needs to be said'), group: 'The copy', help: 'The point in two sentences; the full copy is in the version below.' },
      { ...f.text('approved_copy_reference', 'Copy or file version to review'), group: 'The copy', help: 'A link or a document name and version, so the reviewer reads the same words you mean.' },
      { ...f.yesNo('has_images', 'Does it include images or video?', false), group: 'The copy', sample: false },
      { ...f.choice('image_rights', 'Do we have the rights to them?', ['ours', 'licensed', 'not_sure'], false), group: 'The copy', requiredWhen: when.yes('has_images') },
      { ...f.yesNo('people_identifiable', 'Does it identify anyone?'), group: 'The copy', sample: false },
      { ...f.notes('people_named', 'Who, and how they appear', true), group: 'People in it' },
      { ...f.choice('consent_status', 'Have they agreed?', ['yes_in_writing', 'yes_verbally', 'not_yet']), group: 'People in it' },
      { ...f.yesNo('includes_children', 'Are any of them under eighteen?'), group: 'People in it', help: 'A parent or guardian must have agreed, in writing.' },
      { ...f.date('release_date', 'Planned release date'), group: 'Timing' },
      { ...f.time('release_time', 'Time', false), group: 'Timing' },
      { ...f.yesNo('embargoed', 'Is it embargoed or tied to an announcement?', false), group: 'Timing', sample: false },
      { ...f.notes('timing_notes', 'Anything about the timing', false), group: 'Timing', requiredWhen: when.yes('embargoed') },
      f.recorded('published_link_reference', 'Published link or release reference'),
    ],
  },
  {
    key: 'crisis_statement', name: 'Urgent statement request', category: 'Communications',
    summary: 'A time-critical public statement asked for with what is confirmed, who is affected, who is asking and the proposed words, checked by the right people before it is issued.',
    audience: 'For teams responding to an incident or breaking story.', outcome: 'An authorised statement is issued or a documented decision is made to withhold it.',
    respondents: 'The incident lead or person requesting a statement.', ownerName: 'Communications',
    approvals: [{ key: 'comms', name: 'Communications check', byRole: 'comms_lead', dueInHours: 4 }, { key: 'authority', name: 'Authorised spokesperson', byRole: 'department_head', dueInHours: 6 }],
    task: { key: 'issue_statement', name: 'Issue or withhold the statement', byRole: 'process_owner', description: 'Verify facts and affected people, release only authorised wording, or document why no statement was issued.', requiredFields: ['statement_decision_reference'] },
    completionMessage: 'The statement decision and release record are filed.', notes: ['This process does not override an incident response or legal notification duty.'], retentionDays: 1825,
    groups: {
      'The incident': {},
      'Who is affected': {},
      'Who is asking': { description: 'A statement nobody has asked for is sometimes still needed; say so.' },
      'Press pressure': { visibleWhen: when.yes('press_asking') },
      'The statement': {},
    },
    fields: [
      { ...f.text('incident_reference', 'Incident reference'), group: 'The incident', help: 'From the incident log, so the two records meet.' },
      { ...f.choice('incident_kind', 'What kind of incident', ['service_outage', 'safety', 'data_breach', 'staff_conduct', 'legal', 'reputational', 'other']), group: 'The incident' },
      { ...f.notes('confirmed_facts', 'Facts confirmed so far'), group: 'The incident', help: 'Only what is confirmed. Put what is suspected in the next box.' },
      { ...f.notes('unconfirmed', 'What is suspected but not confirmed', false), group: 'The incident' },
      { ...f.yesNo('still_developing', 'Is it still developing?'), group: 'The incident' },
      { ...f.choice('audience', 'Intended audience', ['public', 'staff', 'customers', 'media', 'regulator']), group: 'Who is affected' },
      { ...f.yesNo('people_harmed', 'Has anyone been harmed?'), group: 'Who is affected', sample: false, help: 'A yes means the families are told before any statement goes out.' },
      { ...f.yesNo('regulator_involved', 'Is a regulator or the police involved?', false), group: 'Who is affected', sample: false },
      { ...f.yesNo('press_asking', 'Is the press already asking?'), group: 'Who is asking', sample: false },
      { ...f.yesNo('already_public', 'Is it already public, anywhere?', false), group: 'Who is asking', sample: false },
      { ...f.text('press_outlets', 'Which outlets'), group: 'Press pressure' },
      { ...f.date('press_deadline_date', 'Earliest deadline', false), group: 'Press pressure' },
      { ...f.time('press_deadline_time', 'At', false), group: 'Press pressure' },
      { ...f.date('response_due', 'Response needed by'), group: 'The statement' },
      { ...f.time('response_due_time', 'At', false), group: 'The statement' },
      { ...f.notes('proposed_words', 'Proposed wording'), group: 'The statement', help: 'A draft is fine. Say what you can confirm, what you are doing, and when you will say more.' },
      { ...f.person('spokesperson_wanted', 'Who should be named as speaking', false), group: 'The statement' },
      f.recorded('statement_decision_reference', 'Statement release or withholding reference'),
    ],
  },
  {
    key: 'website_correction', name: 'Website correction', category: 'Communications',
    summary: 'An inaccurate public page reported with where it is, what is wrong and what it should say, corrected by its owner with a record of the change.',
    audience: 'For teams whose website changes need a check.', outcome: 'The corrected page is live and checked.',
    respondents: 'Anyone who spots an issue.', ownerName: 'Communications',
    approvals: [{ key: 'editor', name: 'Editorial review', byRole: 'comms_lead', dueInHours: 8 }],
    task: { key: 'correct_page', name: 'Correct and verify the page', byRole: 'process_owner', description: 'Confirm the correct information with its owner, update the page and check the live result.', requiredFields: ['corrected_page_reference'] },
    completionMessage: 'The corrected page has been checked and recorded.', retentionDays: 1095,
    groups: {
      'The page': {},
      'What is wrong': {},
      'A wrong fact': { description: 'Say what is right, and how you know.', visibleWhen: when.is('problem_kind', 'fact') },
      'A broken link': { visibleWhen: when.is('problem_kind', 'broken_link') },
      'Urgency': {},
    },
    fields: [
      { ...f.url('page_url', 'Page address', true), group: 'The page', help: 'Copy it from the address bar.' },
      { ...f.text('page_section', 'Where on the page', false), group: 'The page', help: 'A heading or a paragraph number if the page is long.' },
      { ...f.choice('problem_kind', 'What is wrong?', ['outdated', 'fact', 'broken_link', 'accessibility', 'spelling_or_grammar', 'other']), group: 'What is wrong' },
      { ...f.notes('current_problem', 'What needs correcting'), group: 'What is wrong', help: 'Quote the wrong text so it can be found.' },
      { ...f.notes('proposed_correction', 'Suggested correction', false), group: 'What is wrong' },
      { ...f.text('source_of_truth', 'Where the correct information is', false), group: 'A wrong fact', help: 'A document, a policy, a person who owns the fact.' },
      { ...f.person('fact_owner', 'Who owns this information', false), group: 'A wrong fact' },
      { ...f.url('broken_link_target', 'The link that fails', false), group: 'A broken link' },
      { ...f.url('link_should_go_to', 'Where it should go, if you know', false), group: 'A broken link' },
      { ...f.choice('urgency', 'How urgent?', ['routine', 'this_week', 'today']), group: 'Urgency', help: 'Today: it is misleading people now, or it is a legal or safety matter.' },
      { ...f.yesNo('legal_or_safety', 'Is it a legal, safety or accessibility matter?', false), group: 'Urgency', sample: false },
      { ...f.yesNo('reported_elsewhere', 'Has anyone else reported it?', false), group: 'Urgency', sample: false },
      f.recorded('corrected_page_reference', 'Corrected page reference'),
    ],
  },

  // Customer
  {
    key: 'return_replacement', name: 'Return or replacement request', category: 'Customer',
    summary: 'A product issue taken with the order, the item, what is wrong, its condition and the remedy wanted, checked against the order and resolved with a recorded return or replacement.',
    audience: 'For a support team handling product returns.', outcome: 'The customer receives a decision and the agreed remedy is recorded.',
    respondents: 'A customer.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Support review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'arrange_remedy', name: 'Arrange the agreed remedy', byRole: 'process_owner', description: 'Check the order, return condition and applicable terms; arrange the approved remedy in the order system and record its reference.', requiredFields: ['remedy_reference'] },
    completionMessage: 'The agreed return or replacement has been arranged.', notes: ['Any refund is performed separately in the payment provider after approval.'], retentionDays: 2190,
    groups: {
      'The order': {},
      'The item': {},
      'The fault': { visibleWhen: when.oneOf('issue_kind', ['damaged', 'faulty']) },
      'The wrong item': { visibleWhen: when.is('issue_kind', 'wrong_item') },
      'What you would like': {},
      'Sending it back': { visibleWhen: when.no('item_unopened') },
    },
    fields: [
      { ...f.text('order_number', 'Order number'), group: 'The order', help: 'On your confirmation email or the delivery note.' },
      { ...f.date('ordered_on', 'When you ordered', false), group: 'The order' },
      { ...f.date('received_on', 'Date received'), group: 'The order', help: 'Return windows run from this date.' },
      { ...f.text('item_name', 'Item'), group: 'The item' },
      { ...f.number('quantity_affected', 'How many of them', false), group: 'The item', constraints: { min: 1, max: 100 } },
      { ...f.choice('issue_kind', 'What is wrong?', ['unwanted', 'damaged', 'faulty', 'wrong_item', 'missing_parts']), group: 'The item' },
      { ...f.notes('issue_detail', 'Describe the issue'), group: 'The item' },
      { ...f.yesNo('item_unopened', 'Is it unopened and unused?'), group: 'The item', help: 'Unwanted items usually need to be. Faulty ones do not.' },
      { ...f.choice('fault_noticed', 'When you noticed', ['on_opening', 'first_use', 'after_some_use'], false), group: 'The fault' },
      { ...f.yesNo('has_photos', 'Do you have photographs of it?', false), group: 'The fault', help: 'The team will ask for them if they help; do not upload them here.' },
      { ...f.yesNo('safety_concern', 'Could it be unsafe?', false), group: 'The fault', help: 'A yes is looked at the same day.' },
      { ...f.text('item_received_instead', 'What you received instead', false), group: 'The wrong item' },
      { ...f.yesNo('still_have_it', 'Do you still have it?', false), group: 'The wrong item' },
      { ...f.choice('preferred_remedy', 'What would you prefer?', ['replacement', 'refund', 'repair', 'store_credit']), group: 'What you would like' },
      { ...f.choice('return_method', 'How you would return it', ['post', 'drop_off', 'collection', 'not_sure'], false), group: 'Sending it back' },
      { ...f.yesNo('has_packaging', 'Do you still have the packaging?', false), group: 'Sending it back' },
      f.recorded('remedy_reference', 'Return or remedy reference'),
    ],
  },
  {
    key: 'delivery_problem', name: 'Delivery problem', category: 'Customer',
    summary: 'A missing, late or damaged delivery taken with the order, the tracking, what happened and where it should have gone, investigated and resolved.',
    audience: 'For customer teams tracing shipments.', outcome: 'The delivery issue is investigated and the customer receives the agreed outcome.',
    respondents: 'A customer.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Delivery support review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'trace_delivery', name: 'Trace and resolve delivery', byRole: 'process_owner', description: 'Check tracking and carrier evidence, agree the next action with the customer and record the carrier or replacement reference.', requiredFields: ['delivery_resolution_reference'] },
    completionMessage: 'The delivery issue and agreed next action have been recorded.', retentionDays: 2190,
    groups: {
      'The order': {},
      'What happened': {},
      'Marked as delivered': { description: 'Carriers sometimes leave parcels with a neighbour or in a safe place.', visibleWhen: when.is('delivery_issue', 'missing') },
      'Damaged': { visibleWhen: when.is('delivery_issue', 'damaged') },
      'Wrong address': { visibleWhen: when.is('delivery_issue', 'wrong_address') },
      'Putting it right': {},
    },
    fields: [
      { ...f.text('order_number', 'Order number'), group: 'The order' },
      { ...f.text('tracking_number', 'Tracking number', false), group: 'The order', help: 'From the dispatch email if you have it.' },
      { ...f.date('expected_on', 'Expected delivery date'), group: 'The order' },
      { ...f.choice('delivery_issue', 'What happened?', ['late', 'missing', 'damaged', 'wrong_address', 'part_missing']), group: 'What happened' },
      { ...f.notes('delivery_detail', 'Tell us what happened'), group: 'What happened' },
      { ...f.yesNo('tracking_says_delivered', 'Does the tracking say it was delivered?'), group: 'Marked as delivered' },
      { ...f.yesNo('checked_neighbours', 'Have you checked with neighbours and safe places?'), group: 'Marked as delivered' },
      { ...f.date('tracking_delivered_on', 'The date it says', false), group: 'Marked as delivered' },
      { ...f.choice('damage_extent', 'How bad', ['packaging_only', 'item_damaged_but_usable', 'item_unusable']), group: 'Damaged' },
      { ...f.yesNo('has_photos', 'Do you have photographs?', false), group: 'Damaged', help: 'Of the box and the item. The team will ask for them.' },
      { ...f.notes('address_used', 'The address it went to, if you know', false), group: 'Wrong address' },
      { ...f.yesNo('address_was_correct', 'Was the address on your order correct?'), group: 'Wrong address' },
      { ...f.choice('preferred_outcome', 'What would you like', ['redeliver', 'replacement', 'refund', 'just_find_it']), group: 'Putting it right' },
      { ...f.choice('preferred_contact', 'How should we contact you?', ['email', 'phone']), group: 'Putting it right' },
      { ...f.phone('contact_phone', 'Phone number'), group: 'Putting it right', requiredWhen: when.is('preferred_contact', 'phone') },
      f.recorded('delivery_resolution_reference', 'Delivery resolution reference'),
    ],
  },
  {
    key: 'service_change', name: 'Service change request', category: 'Customer',
    summary: 'A customer change to an active service taken with the account, what should change, from when and why, checked for eligibility and authority and carried through.',
    audience: 'For subscription or service support teams.', outcome: 'The requested change is applied or declined with the reason recorded.',
    respondents: 'A customer or account contact.', ownerName: 'Customer operations',
    approvals: [{ key: 'support', name: 'Service change review', byRole: 'support_supervisor', dueInHours: 24 }],
    task: { key: 'apply_change', name: 'Apply and confirm the change', byRole: 'process_owner', description: 'Check authority and applicable terms, apply the agreed change in the service system and send confirmation.', requiredFields: ['service_change_reference'] },
    completionMessage: 'Your service change has been applied and recorded.', notes: ['This form does not automatically cancel billing or issue a refund.'], retentionDays: 2190,
    groups: {
      'The account': {},
      'The change': {},
      'A new plan': { visibleWhen: when.is('change_kind', 'plan') },
      'A pause': { visibleWhen: when.is('change_kind', 'pause') },
      'Cancelling': { description: 'Sorry to see you go. This helps us do it cleanly.', visibleWhen: when.is('change_kind', 'cancel') },
      'New details': { visibleWhen: when.oneOf('change_kind', ['address', 'contact']) },
    },
    fields: [
      { ...f.text('account_reference', 'Account or service reference'), group: 'The account' },
      { ...f.yesNo('account_authority', 'Are you the account holder or authorised on it?'), group: 'The account', help: 'We can only change an account on the say of somebody named on it.' },
      { ...f.text('authority_detail', 'Your role on the account', false), group: 'The account', requiredWhen: when.no('account_authority') },
      { ...f.choice('change_kind', 'Requested change', ['plan', 'address', 'contact', 'pause', 'cancel']), group: 'The change' },
      { ...f.date('effective_from', 'When should it start?'), group: 'The change', help: 'Some changes take effect at the next billing date.' },
      { ...f.notes('change_detail', 'What should change?'), group: 'The change' },
      { ...f.text('new_plan', 'Which plan', false), group: 'A new plan' },
      { ...f.choice('plan_reason', 'Why', ['need_more', 'need_less', 'cost', 'other'], false), group: 'A new plan' },
      { ...f.date('pause_until', 'Resume on', false), group: 'A pause', help: 'Leave blank if you are not sure yet.' },
      { ...f.choice('cancel_reason', 'Reason', ['cost', 'not_using_it', 'moving_to_another_provider', 'service_problems', 'other'], false), group: 'Cancelling' },
      { ...f.notes('cancel_detail', 'Anything you would like us to know', false), group: 'Cancelling' },
      { ...f.yesNo('understands_notice', 'Do you understand any notice period on your plan applies?'), group: 'Cancelling' },
      { ...f.notes('new_details', 'The new address or contact details', true), group: 'New details' },
      { ...f.choice('confirm_by', 'Send confirmation by', ['email', 'post', 'text_message'], false), group: 'The change' },
      f.recorded('service_change_reference', 'Service change reference'),
    ],
  },

  // Education
  {
    key: 'assessment_extension', name: 'Assessment extension', category: 'Education',
    summary: 'A deadline change asked for with the assessment, the dates, the reason and what evidence supports it, reviewed against course rules and communicated to the learner.',
    audience: 'For schools and training providers managing coursework deadlines.', outcome: 'An extension decision and new deadline are recorded.',
    respondents: 'A learner or parent acting for one.', ownerName: 'Academic office',
    approvals: [{ key: 'tutor', name: 'Course tutor', byRole: 'course_tutor', dueInHours: 48 }],
    task: { key: 'update_deadline', name: 'Update the assessment record', byRole: 'process_owner', description: 'Apply the approved deadline in the learning system, notify the learner and record the change reference.', requiredFields: ['extension_reference'] },
    completionMessage: 'The extension decision and any new deadline have been recorded.', notes: ['Evidence requirements and allowable extensions depend on the provider’s policy.'], retentionDays: 1095,
    groups: {
      'The assessment': {},
      'The dates': {},
      'Why': {},
      'Evidence': { description: 'Extensions over a week usually need it. Do not attach medical notes here; the tutor will say how to send them.', visibleWhen: when.yes('has_evidence') },
      'Other deadlines': { visibleWhen: when.yes('other_assessments_affected') },
    },
    fields: [
      { ...f.text('course_name', 'Course'), group: 'The assessment' },
      { ...f.text('assessment_name', 'Assessment'), group: 'The assessment' },
      { ...f.person('tutor_name', 'Your tutor', false), group: 'The assessment' },
      { ...f.date('current_deadline', 'Current deadline'), group: 'The dates' },
      { ...f.date('requested_deadline', 'Requested deadline'), group: 'The dates' },
      { ...f.yesNo('extended_before', 'Has this assessment been extended before?'), group: 'The dates', sample: false },
      { ...f.choice('reason_kind', 'Reason', ['illness', 'bereavement', 'caring_responsibilities', 'technical_problems', 'work_commitments', 'other']), group: 'Why' },
      { ...f.notes('extension_reason', 'Why do you need more time?'), group: 'Why' },
      { ...f.choice('progress', 'How far along you are', ['not_started', 'started', 'mostly_done'], false), group: 'Why' },
      { ...f.yesNo('has_evidence', 'Do you have evidence to support this?'), group: 'Why', sample: false },
      { ...f.choice('evidence_kind', 'What kind', ['medical_note', 'letter', 'employer_confirmation', 'other']), group: 'Evidence' },
      { ...f.yesNo('other_assessments_affected', 'Are other deadlines affected too?'), group: 'Why', sample: false },
      { ...f.notes('other_assessments', 'Which ones', true), group: 'Other deadlines' },
      f.recorded('extension_reference', 'Extension decision reference'),
    ],
  },
  {
    key: 'student_wellbeing', name: 'Student wellbeing concern', category: 'Education',
    summary: 'A concern about a student taken with who, what was seen, when, whether they are safe now and who already knows, routed privately for timely human review.',
    audience: 'For staff who need a clear route to the safeguarding team.', outcome: 'The concern is assessed and a safe follow-up is recorded.',
    respondents: 'A staff member or parent.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'safeguarding', name: 'Safeguarding review', byRole: 'safeguarding_lead', dueInHours: 24 }],
    task: { key: 'follow_up', name: 'Record safeguarding follow-up', byRole: 'safeguarding_lead', description: 'Assess immediate risk, use the organisation’s safeguarding route, make necessary referrals outside this form and record a secure case reference.', requiredFields: ['wellbeing_case_reference'] },
    completionMessage: 'The concern has been reviewed and follow-up recorded by the safeguarding team.', notes: ['Immediate danger needs the local emergency route. Do not use routine email to repeat the private concern.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    groups: {
      'The student': {},
      'What you noticed': {},
      'Right now': {},
      'Who knows': {},
      'About you': {},
    },
    fields: [
      { ...f.person('student_name', 'Student name'), group: 'The student' },
      { ...f.text('class_group', 'Class or group', false), group: 'The student' },
      { ...f.choice('concern_kind', 'Kind of concern', ['wellbeing', 'attendance', 'safety', 'behaviour_change', 'online', 'home_circumstances', 'other']), group: 'What you noticed' },
      { ...f.date('noticed_on', 'When was this noticed?'), group: 'What you noticed' },
      { ...f.choice('how_noticed', 'How', ['saw_it', 'student_told_me', 'another_student_told_me', 'parent_told_me', 'other'], false), group: 'What you noticed' },
      { ...f.private('concern_detail', 'What have you observed?', 'Student welfare details are restricted to the safeguarding team.', true), group: 'What you noticed', help: 'What was said or seen, in their words where you can. Facts, not conclusions.' },
      { ...f.yesNo('pattern', 'Is this part of a pattern you have noticed?', false), group: 'What you noticed', sample: false },
      { ...f.yesNo('immediate_risk', 'Is someone in immediate danger?'), group: 'Right now', sample: false, help: 'If yes, call the emergency services first and then send this.' },
      { ...f.yesNo('student_aware', 'Does the student know you are raising this?', false), group: 'Right now' },
      { ...f.yesNo('parents_aware', 'Do the parents or carers know?', false), group: 'Who knows', sample: false, help: 'The safeguarding lead decides whether and how they are told. Do not contact them about this yourself.' },
      { ...f.yesNo('raised_before', 'Has a concern about this student been raised before, as far as you know?', false), group: 'Who knows', sample: false },
      { ...f.text('others_involved', 'Anyone else involved or aware', false), group: 'Who knows' },
      { ...f.choice('your_role', 'You are', ['teacher', 'support_staff', 'parent_or_carer', 'other_staff', 'other']), group: 'About you' },
      { ...f.phone('contact_phone', 'A number the safeguarding lead can call today'), group: 'About you' },
      f.recorded('wellbeing_case_reference', 'Secure case reference'),
    ],
  },

  // Facilities
  {
    key: 'building_access', name: 'Building access request', category: 'Facilities',
    summary: 'Physical access asked for with who, which areas, what kind, for how long and why, granted for a named person, place and period with a return record.',
    audience: 'For facilities teams managing keys or badges.', outcome: 'Access is authorised, issued and tracked for return.',
    respondents: 'A manager or building user.', ownerName: 'Facilities',
    approvals: [{ key: 'facilities', name: 'Facilities approval', byRole: 'facilities_manager', dueInHours: 24 }],
    task: { key: 'issue_access', name: 'Issue and record access', byRole: 'process_owner', description: 'Confirm identity, area and end date; issue the key or badge, record its identifier and arrange its return.', requiredFields: ['access_issue_reference'] },
    completionMessage: 'The authorised building access has been issued and recorded.', retentionDays: 1825,
    groups: {
      'Who': {},
      'Not a member of staff': { visibleWhen: when.oneOf('person_kind', ['contractor', 'visitor', 'volunteer']) },
      'Where': {},
      'What kind of access': {},
      'Out of hours': { visibleWhen: when.yes('out_of_hours') },
      'How long': {},
    },
    fields: [
      { ...f.person('access_for', 'Who needs access?'), group: 'Who' },
      { ...f.choice('person_kind', 'They are', ['staff', 'contractor', 'visitor', 'volunteer']), group: 'Who' },
      { ...f.yesNo('for_yourself', 'Is this for you?', false), group: 'Who', sample: false },
      { ...f.text('their_organisation', 'Their organisation'), group: 'Not a member of staff' },
      { ...f.yesNo('id_seen', 'Has their identity been checked?'), group: 'Not a member of staff' },
      { ...f.text('area', 'Building or area'), group: 'Where' },
      { ...f.many('restricted_areas', 'Any restricted areas', ['server_room', 'plant_room', 'roof', 'cash_office', 'records_store', 'none']), group: 'Where' },
      { ...f.choice('access_kind', 'Access type', ['badge', 'key', 'visitor_pass', 'temporary_code']), group: 'What kind of access' },
      { ...f.yesNo('out_of_hours', 'Outside normal hours?'), group: 'What kind of access', sample: false },
      { ...f.notes('hours_needed', 'Which hours or days'), group: 'Out of hours' },
      { ...f.yesNo('lone_working', 'Will they be working alone?'), group: 'Out of hours', help: 'A yes brings the lone-working procedure with it.' },
      { ...f.date('access_from', 'Start date'), group: 'How long' },
      { ...f.date('access_until', 'End date'), group: 'How long', help: 'Access is removed on this date. Ask again to extend.' },
      { ...f.notes('business_reason', 'Why is access needed?'), group: 'How long' },
      f.recorded('access_issue_reference', 'Key or badge issue reference'),
    ],
  },

  // Health & safety
  {
    key: 'safety_inspection', name: 'Safety inspection', category: 'Health & safety',
    summary: 'An inspection recorded finding by finding with where, how serious, what was done on the spot and who owns the fix, assigned and closed with evidence.',
    audience: 'For site teams recording routine safety checks.', outcome: 'Findings are made safe, assigned and verified.',
    respondents: 'An inspector or site lead.', ownerName: 'Health and safety',
    approvals: [{ key: 'safety', name: 'Safety lead review', byRole: 'safety_lead', dueInHours: 24 }],
    task: { key: 'close_findings', name: 'Assign and verify findings', byRole: 'safety_lead', description: 'Make urgent hazards safe, assign each finding and due date, verify corrective work and record the inspection log.', requiredFields: ['inspection_log_reference'] },
    completionMessage: 'The inspection findings and corrective actions have been recorded.', retentionDays: 3650,
    groups: {
      'The inspection': {},
      'Findings': { description: 'One line per finding. Nothing found is a valid inspection; say so below.' },
      'Urgent': { description: 'High-risk findings are dealt with before this form is finished.', visibleWhen: when.is('highest_risk', 'high') },
      'Overall': {},
    },
    fields: [
      { ...f.date('inspection_date', 'Inspection date'), group: 'The inspection' },
      { ...f.text('site', 'Site or area'), group: 'The inspection' },
      { ...f.choice('inspection_kind', 'Inspection type', ['routine', 'fire', 'equipment', 'contractor', 'follow_up']), group: 'The inspection' },
      { ...f.person('inspected_with', 'Anyone who inspected with you', false), group: 'The inspection' },
      {
        key: 'finding_lines', label: 'Findings', type: 'repeating_group', required: false, classification: 'internal' as const, group: 'Findings',
        fields: [
          f.text('finding_where', 'Where'),
          f.text('finding_what', 'What was found'),
          f.choice('finding_risk', 'Risk', ['low', 'medium', 'high']),
          { ...f.text('finding_action', 'Action needed', false) },
          { ...f.text('finding_owner', 'Who', false) },
        ],
      },
      { ...f.notes('findings', 'Findings and evidence'), group: 'Findings', help: 'A summary, and where photographs or checklists are kept.' },
      { ...f.choice('highest_risk', 'Highest risk found', ['none', 'low', 'medium', 'high']), group: 'Overall' },
      { ...f.yesNo('area_made_safe', 'Was any urgent hazard made safe?'), group: 'Overall' },
      { ...f.notes('urgent_action_taken', 'What was done, and when', true), group: 'Urgent' },
      { ...f.yesNo('work_stopped', 'Was any work stopped?'), group: 'Urgent' },
      { ...f.person('urgent_told', 'Who was told', false), group: 'Urgent' },
      { ...f.yesNo('previous_actions_closed', 'Were the previous inspection’s actions closed?', false), group: 'Overall' },
      { ...f.date('next_inspection_due', 'Next inspection due', false), group: 'Overall' },
      f.recorded('inspection_log_reference', 'Inspection log reference'),
    ],
  },

  // Healthcare: these request human clinical review; they never prescribe or diagnose.
  {
    key: 'prescription_renewal', name: 'Prescription renewal request', category: 'Healthcare',
    summary: 'A medication renewal asked for with who, which medicines, when the supply runs out, any changes and where to collect, checked by a clinician before a prescription is issued.',
    audience: 'For a clinical team receiving repeat-medication requests.', outcome: 'A clinician decides and records the prescription or follow-up outcome.',
    respondents: 'A patient or authorised carer.', ownerName: 'Clinical administration',
    approvals: [{ key: 'clinician', name: 'Clinician review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'record_renewal', name: 'Record the clinical outcome', byRole: 'clinician', description: 'Check the clinical record, safety and eligibility; prescribe only through the clinical system or arrange a review, then record its reference.', requiredFields: ['renewal_outcome_reference'] },
    completionMessage: 'A clinician has reviewed the request and recorded the next step.', notes: ['Submitting this form is not a prescription. Urgent symptoms need the local urgent-care route.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    groups: {
      'The patient': {},
      'Asking for somebody else': { visibleWhen: when.yes('on_behalf') },
      'The medicines': { description: 'Read by the reviewing clinician only.' },
      'Changes or concerns': { visibleWhen: when.yes('has_concerns') },
      'Collecting it': {},
    },
    fields: [
      { ...f.text('patient_reference', 'Patient record reference'), group: 'The patient' },
      { ...f.person('patient_name', 'Patient name'), group: 'The patient' },
      { ...f.date('patient_dob', 'Date of birth'), group: 'The patient' },
      { ...f.yesNo('on_behalf', 'Are you asking for somebody else?'), group: 'The patient', sample: false },
      { ...f.choice('carer_relationship', 'You are their', ['parent_or_guardian', 'carer', 'family_member', 'care_home_staff']), group: 'Asking for somebody else' },
      { ...f.yesNo('authorised_on_record', 'Are you named on their record as authorised?'), group: 'Asking for somebody else' },
      { ...f.private('medicine_requested', 'Medicine and dose requested', 'Medication information is clinical data for the reviewing clinician.', true), group: 'The medicines', help: 'Each medicine on its own line, as it appears on the label.' },
      { ...f.date('supply_runs_out', 'When will your supply run out?'), group: 'The medicines', help: 'Ask a week ahead where you can.' },
      { ...f.yesNo('all_repeats', 'Are these all on your repeat list?', false), group: 'The medicines' },
      { ...f.date('last_review', 'When were they last reviewed, roughly?', false), group: 'The medicines' },
      { ...f.yesNo('has_concerns', 'Any recent changes or concerns?'), group: 'The medicines', sample: false },
      { ...f.private('recent_changes', 'Tell the clinician', 'Treatment concerns must be reviewed privately by a clinician.', true), group: 'Changes or concerns' },
      { ...f.yesNo('wants_review_call', 'Would you like a clinician to call you about it?', false), group: 'Changes or concerns' },
      { ...f.choice('collection', 'Where to send the prescription', ['usual_pharmacy', 'a_different_pharmacy', 'collect_from_practice', 'electronic_to_my_app']), group: 'Collecting it' },
      { ...f.text('pharmacy_name', 'Which pharmacy', false), group: 'Collecting it', requiredWhen: when.is('collection', 'a_different_pharmacy') },
      { ...f.phone('contact_phone', 'A number if the clinician needs to call'), group: 'Collecting it' },
      f.recorded('renewal_outcome_reference', 'Clinical renewal outcome reference'),
    ],
  },
  {
    key: 'test_result_enquiry', name: 'Test result enquiry', category: 'Healthcare',
    summary: 'A test result query taken with who, which test, when, what is being asked and how to call safely, routed for identity checking and clinical interpretation.',
    audience: 'For clinics receiving patient result enquiries.', outcome: 'An authorised clinician gives the result or arranges follow-up through a safe channel.',
    respondents: 'A patient or authorised representative.', ownerName: 'Clinical administration',
    approvals: [{ key: 'clinician', name: 'Clinician review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'respond_result', name: 'Provide result or arrange follow-up', byRole: 'clinician', description: 'Verify identity and authorisation in the clinical record. Call the supplied number through the approved clinical process, interpret the result or arrange follow-up, and record the contact reference. Do not put the result in PatForm or a routine email.', requiredFields: ['result_contact_reference'] },
    completionMessage: 'The clinical team has recorded how your result enquiry was handled.', notes: ['The phone number is for arranging a safe call; staff must verify identity before discussing results. Do not put test results in routine notification emails. This form does not display or diagnose a result.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    groups: {
      'The patient': {},
      'Asking for somebody else': { visibleWhen: when.yes('on_behalf') },
      'The test': {},
      'Your question': { description: 'Read by the clinician only. The result itself is never written here.' },
      'A safe call': {},
    },
    fields: [
      { ...f.text('patient_reference', 'Patient record reference'), group: 'The patient' },
      { ...f.person('patient_name', 'Patient name'), group: 'The patient' },
      { ...f.date('patient_dob', 'Date of birth'), group: 'The patient', help: 'Used to check identity before anything is discussed.' },
      { ...f.yesNo('on_behalf', 'Are you asking for somebody else?'), group: 'The patient', sample: false },
      { ...f.choice('relationship', 'You are their', ['parent_or_guardian', 'carer', 'family_member', 'other']), group: 'Asking for somebody else' },
      { ...f.yesNo('has_consent', 'Have they agreed to you receiving their result?'), group: 'Asking for somebody else', help: 'Results are only discussed with the patient or somebody they have authorised.' },
      { ...f.choice('test_kind', 'Type of test', ['blood', 'imaging', 'screening', 'swab_or_sample', 'other']), group: 'The test' },
      { ...f.date('test_on', 'Date of test'), group: 'The test' },
      { ...f.text('test_where', 'Where it was done', false), group: 'The test', help: 'The practice, a hospital, a screening unit.' },
      { ...f.yesNo('told_when_to_expect', 'Were you told when to expect the result?', false), group: 'The test' },
      { ...f.private('enquiry_detail', 'What would you like to ask?', 'A result enquiry may reveal sensitive clinical circumstances.'), group: 'Your question' },
      { ...f.choice('worry_level', 'How worried are you', ['just_checking', 'somewhat', 'very'], false), group: 'Your question', help: 'It helps the clinician decide who to call first.' },
      { ...f.phone('safe_phone', 'Phone number for a safe call', true), group: 'A safe call' },
      { ...f.text('safe_times', 'Times that are safe to call', false), group: 'A safe call' },
      { ...f.yesNo('voicemail_ok', 'May we leave a voicemail saying we called?'), group: 'A safe call', help: 'The message would never contain the result.' },
      { ...f.yesNo('needs_interpreter', 'Do you need an interpreter?', false), group: 'A safe call' },
      f.recorded('result_contact_reference', 'Result response reference'),
    ],
  },
  {
    key: 'care_plan_change', name: 'Care plan change request', category: 'Healthcare',
    summary: 'A proposed care-plan change taken with the patient, the plan version, what should change, why, from when and who agrees, reviewed clinically and recorded against the right version.',
    audience: 'For care teams coordinating changes without losing the decision trail.', outcome: 'A clinician approves or declines the change and the care plan version is updated.',
    respondents: 'A patient, carer or care-team member.', ownerName: 'Care coordination',
    approvals: [{ key: 'clinical', name: 'Clinical review', byRole: 'clinician', dueInHours: 24 }],
    task: { key: 'update_plan', name: 'Update and communicate the care plan', byRole: 'clinician', description: 'Check consent, assess the proposed change, update the approved care plan in the clinical system and notify the relevant care team.', requiredFields: ['care_plan_version_reference'] },
    completionMessage: 'The care-plan decision and updated version have been recorded.', notes: ['A change is not effective until the clinical team confirms it in the care record.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    groups: {
      'The patient and the plan': {},
      'The change': {},
      'Medication': { description: 'Medication changes are made only by a prescriber.', visibleWhen: when.is('requested_change', 'medication') },
      'Why': { description: 'Read by the clinical reviewer.' },
      'Who agrees': {},
      'Not involved': { visibleWhen: when.no('patient_involved') },
    },
    fields: [
      { ...f.text('patient_reference', 'Patient record reference'), group: 'The patient and the plan' },
      { ...f.text('current_plan_version', 'Current plan version'), group: 'The patient and the plan', help: 'On the front of the plan.' },
      { ...f.choice('your_role', 'You are', ['the_patient', 'a_carer_or_family_member', 'a_care_worker', 'a_clinician', 'other']), group: 'The patient and the plan' },
      { ...f.choice('requested_change', 'What needs changing?', ['support', 'appointments', 'goals', 'medication', 'other']), group: 'The change' },
      { ...f.date('needed_from', 'Requested start date'), group: 'The change' },
      { ...f.choice('urgency', 'How soon', ['next_review', 'this_week', 'now'], false), group: 'The change' },
      { ...f.private('medication_detail', 'Which medicine, and what change', 'Medication detail is clinical data for the prescriber.', true), group: 'Medication' },
      { ...f.yesNo('prescriber_aware', 'Is the prescriber aware?'), group: 'Medication' },
      { ...f.private('change_reason', 'Why is a change needed?', 'The reason may contain private health information.', true), group: 'Why', help: 'What has changed for the patient, and what the plan does not cover.' },
      { ...f.yesNo('patient_involved', 'Has the patient been involved in this request?'), group: 'Who agrees' },
      { ...f.yesNo('family_aware', 'Is the family or main carer aware?', false), group: 'Who agrees' },
      { ...f.notes('why_not_involved', 'Why not, and how they will be involved', true), group: 'Not involved' },
      { ...f.yesNo('capacity_concern', 'Is there a concern about the patient’s capacity to decide?'), group: 'Not involved' },
      { ...f.phone('contact_phone', 'A number for the reviewer'), group: 'Who agrees' },
      f.recorded('care_plan_version_reference', 'Updated care plan version'),
    ],
  },

  // Legal
  {
    key: 'nda_request', name: 'Non-disclosure agreement request', category: 'Legal',
    summary: 'A confidentiality agreement checked for parties, purpose and approved wording before signature.',
    audience: 'For teams sharing confidential material with an outside party.', outcome: 'The approved NDA is signed outside this process and filed by version.',
    respondents: 'The relationship owner.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal review', byRole: 'legal_reviewer', dueInHours: 120 }, { key: 'signatory', name: 'Authorised signatory', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'file_nda', name: 'Verify signature and file NDA', byRole: 'process_owner', description: 'Check the executed agreement matches the approved version, file it and record the document reference.', requiredFields: ['signed_nda_reference'] },
    completionMessage: 'The signed NDA has been checked and filed.', notes: ['PatForm records the approval and filing reference; the agreement is signed separately.'], retentionDays: 3650,
    fields: [f.text('counterparty', 'Other party'), f.choice('nda_kind', 'Who discloses?', ['mutual', 'us_only', 'other_party_only']), f.notes('sharing_purpose', 'Purpose of sharing'), f.date('needed_by', 'Needed by'), f.text('draft_version', 'Draft document version'), f.choice('information_kind', 'Information involved', ['commercial', 'technical', 'personal_data', 'other']), f.recorded('signed_nda_reference', 'Signed NDA reference')],
  },
  {
    key: 'legal_hold', name: 'Legal hold request', category: 'Legal',
    summary: 'A preservation request scoped and issued before records are altered or deleted.',
    audience: 'For legal teams handling disputes or investigations.', outcome: 'Relevant custodians are notified and preservation is documented.',
    respondents: 'Legal or an authorised case lead.', ownerName: 'Legal',
    approvals: [{ key: 'counsel', name: 'Counsel review', byRole: 'legal_reviewer', dueInHours: 120 }],
    task: { key: 'issue_hold', name: 'Issue and record the hold', byRole: 'process_owner', description: 'Define custodians, systems, date range and review date; issue the hold through the approved records process and record acknowledgements.', requiredFields: ['hold_notice_reference'] },
    completionMessage: 'The preservation notice and scope have been recorded.', notes: ['Do not use this form as the preservation mechanism itself; retention and deletion systems must be updated separately.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.text('matter_reference', 'Matter reference'), f.date('triggered_on', 'When was the need identified?'), f.private('matter_summary', 'Why is preservation needed?', 'Legal dispute details are privileged or otherwise sensitive.', true), f.notes('systems_in_scope', 'Systems and records in scope'), f.notes('custodian_roles', 'Custodian roles or teams'), f.date('review_on', 'Review date'), f.recorded('hold_notice_reference', 'Hold notice reference')],
  },
  {
    key: 'dispute_intake', name: 'Dispute or claim intake', category: 'Legal',
    summary: 'A legal claim or threatened dispute sent to counsel with dates and documents tracked.',
    audience: 'For teams who receive formal complaints or legal letters.', outcome: 'Counsel has triaged the matter and recorded its response owner and deadline.',
    respondents: 'Whoever received the claim.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal triage', byRole: 'legal_reviewer', dueInHours: 120 }],
    task: { key: 'open_matter', name: 'Open and assign the legal matter', byRole: 'process_owner', description: 'Verify the response deadline, preserve relevant material, assign counsel and record the matter reference.', requiredFields: ['legal_matter_reference'] },
    completionMessage: 'The claim has been triaged and assigned to legal counsel.', notes: ['A filed claim or imminent deadline requires immediate direct notice to counsel; this form alone does not protect a deadline.'], retentionDays: 3650, sensitivityCeiling: 'restricted',
    fields: [f.date('received_on', 'Date received'), f.text('claimant', 'Claimant or representative'), f.choice('claim_kind', 'Type of dispute', ['contract', 'employment', 'property', 'injury', 'other']), f.date('response_due', 'Stated response deadline'), f.private('claim_summary', 'What is alleged?', 'Allegations and legal strategy must stay with the legal team.', true), f.text('document_reference', 'Letter or document reference'), f.recorded('legal_matter_reference', 'Legal matter reference')],
  },
  {
    key: 'policy_legal_review', name: 'Policy legal review', category: 'Legal',
    summary: 'A proposed policy checked for legal obligations and approved wording before adoption.',
    audience: 'For teams updating internal policies.', outcome: 'The approved policy version and publication decision are recorded.',
    respondents: 'A policy owner.', ownerName: 'Legal',
    approvals: [{ key: 'legal', name: 'Legal review', byRole: 'legal_reviewer', dueInHours: 120 }, { key: 'owner', name: 'Policy owner approval', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'publish_policy', name: 'Publish the approved version', byRole: 'process_owner', description: 'Check the final text, effective date and staff notice, then publish the approved version and record its reference.', requiredFields: ['policy_version_reference'] },
    completionMessage: 'The approved policy version has been recorded and issued.', retentionDays: 3650,
    fields: [f.text('policy_name', 'Policy name'), f.text('current_version', 'Current version'), f.notes('proposed_change', 'What should change?'), f.notes('reason', 'Why is the change needed?'), f.date('effective_on', 'Proposed effective date'), f.choice('affected_group', 'Who is affected?', ['staff', 'customers', 'suppliers', 'public']), f.recorded('policy_version_reference', 'Published policy version')],
  },

  // Procurement
  {
    key: 'supplier_change', name: 'Supplier details change', category: 'Procurement',
    summary: 'A supplier update verified independently before a vendor record changes.',
    audience: 'For teams guarding against invoice and bank-change fraud.', outcome: 'The supplier change is verified and the vendor record updated.',
    respondents: 'The internal supplier owner.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'finance', name: 'Finance verification', byRole: 'finance_reviewer', dueInHours: 120 }],
    task: { key: 'apply_vendor_change', name: 'Verify and update supplier record', byRole: 'process_owner', description: 'Verify any payment-detail change through a known independent contact, record the verification and update the vendor master.', requiredFields: ['vendor_change_reference'] },
    completionMessage: 'The verified supplier change has been recorded.', notes: ['Do not enter bank account details in this form. Verification must use a separately known contact route.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.text('vendor_reference', 'Existing vendor reference'), f.text('supplier_name', 'Supplier name'), f.choice('change_kind', 'What is changing?', ['contact', 'address', 'tax_details', 'payment_details']), f.notes('requested_change', 'Describe the change without bank numbers'), f.date('requested_on', 'Date requested'), { ...f.text('verification_reference', 'Independent verification reference', false), classification: 'restricted', reason: 'Evidence of payment-detail verification is limited to procurement and finance.' }, f.recorded('vendor_change_reference', 'Updated vendor record reference')],
  },
  {
    key: 'purchase_order_change', name: 'Purchase order change', category: 'Procurement',
    summary: 'A price, quantity or delivery change approved before an order is amended.',
    audience: 'For teams managing changes to placed purchase orders.', outcome: 'The approved change is reflected in the purchase order and supplier notice.',
    respondents: 'The requisitioner or buyer.', ownerName: 'Procurement',
    approvals: [{ key: 'buyer', name: 'Buyer review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'budget', name: 'Budget owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'amend_order', name: 'Amend and reissue the order', byRole: 'process_owner', description: 'Check the current commitment, amend only the approved lines, send the revision to the supplier and record the new order version.', requiredFields: ['amended_po_reference'] },
    completionMessage: 'The amended purchase order has been issued and recorded.', retentionDays: 2555,
    fields: [f.text('po_number', 'Purchase order number'), f.text('supplier_name', 'Supplier'), f.choice('change_kind', 'Change needed', ['quantity', 'price', 'delivery', 'scope', 'cancel_line']), f.notes('old_and_new', 'Current and proposed terms'), f.money('revised_total', 'Revised order total'), f.date('needed_by', 'When is the change needed?'), f.recorded('amended_po_reference', 'Amended PO version')],
  },
  {
    key: 'bid_evaluation', name: 'Bid evaluation', category: 'Procurement',
    summary: 'Supplier offers compared against agreed criteria with conflicts and the award recorded.',
    audience: 'For buyers running a competitive quotation or tender.', outcome: 'An award recommendation is reviewed and the decision documented.',
    respondents: 'The buyer running the comparison.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'budget', name: 'Budget owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'record_award', name: 'Notify bidders and file evaluation', byRole: 'process_owner', description: 'File the evaluation and conflict declarations, notify bidders through the approved route and record the award reference.', requiredFields: ['award_decision_reference'] },
    completionMessage: 'The supplier award decision and evaluation have been recorded.', notes: ['Use your organisation’s procurement thresholds, scoring method and conflict policy.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.text('sourcing_reference', 'Sourcing reference'), f.text('requirement', 'What is being bought?'), f.money('estimated_value', 'Estimated value'), f.text('bids_received', 'Bid references received'), f.notes('criteria_result', 'Evaluation against agreed criteria'), f.yesNo('conflict_declared', 'Has any evaluator declared a conflict?'), f.private('conflict_detail', 'Conflict handling detail', 'Evaluator conflicts require restricted review.'), f.recorded('award_decision_reference', 'Award decision reference')],
  },
  {
    key: 'contract_renewal', name: 'Supplier contract renewal', category: 'Procurement',
    summary: 'A renewal reviewed before notice deadlines and spending commitments take effect.',
    audience: 'For teams tracking recurring supplier contracts.', outcome: 'The contract is renewed, renegotiated or ended with the action recorded.',
    respondents: 'The contract owner.', ownerName: 'Procurement',
    approvals: [{ key: 'procurement', name: 'Procurement review', byRole: 'procurement_lead', dueInHours: 120 }, { key: 'owner', name: 'Service owner', byRole: 'department_head', dueInHours: 120 }],
    task: { key: 'execute_renewal', name: 'Carry out the renewal decision', byRole: 'process_owner', description: 'Check notice terms and approved value, send the renewal or termination notice outside PatForm and file the resulting document.', requiredFields: ['renewal_action_reference'] },
    completionMessage: 'The contract renewal decision and action have been recorded.', notes: ['The contract’s actual notice date must be checked against the signed terms; this form does not send legal notice.'], retentionDays: 2555,
    fields: [f.text('supplier_name', 'Supplier'), f.text('contract_reference', 'Contract reference'), f.date('expires_on', 'Contract expiry'), f.date('notice_by', 'Notice deadline'), f.choice('proposed_action', 'Proposed action', ['renew', 'renegotiate', 'retender', 'end']), f.money('renewal_value', 'Proposed renewal value'), f.notes('performance_review', 'Performance and alternatives'), f.recorded('renewal_action_reference', 'Renewal or termination action reference')],
  },

  // Property
  {
    key: 'move_in_inspection', name: 'Move-in inspection', category: 'Property',
    summary: 'A property condition check agreed and filed before occupancy begins.',
    audience: 'For property teams recording condition and handover.', outcome: 'The condition record and keys are documented for the tenancy.',
    respondents: 'A property manager or incoming occupier.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager review', byRole: 'property_manager', dueInHours: 48 }],
    task: { key: 'file_condition', name: 'File inventory and handover', byRole: 'process_owner', description: 'Check the signed condition record and meter readings, agree any defects and record the handover reference.', requiredFields: ['move_in_record_reference'] },
    completionMessage: 'The move-in condition and handover record have been filed.', retentionDays: 2555,
    fields: [f.text('property_reference', 'Property reference'), f.date('inspection_on', 'Inspection date'), f.date('tenancy_starts', 'Tenancy start date'), f.notes('condition_summary', 'Condition and defects'), f.text('meter_readings', 'Meter readings', false), f.yesNo('keys_received', 'Were keys received?'), f.text('inventory_document_reference', 'Inventory document reference'), f.recorded('move_in_record_reference', 'Move-in record reference')],
  },
  {
    key: 'deposit_return', name: 'Deposit return review', category: 'Property',
    summary: 'Proposed deposit deductions checked against evidence before a return is processed.',
    audience: 'For property teams closing a tenancy.', outcome: 'A supported deposit decision is communicated and its payment reference recorded.',
    respondents: 'A property manager or tenancy administrator.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager', byRole: 'property_manager', dueInHours: 48 }, { key: 'finance', name: 'Finance check', byRole: 'finance_reviewer', dueInHours: 72 }],
    task: { key: 'process_deposit', name: 'Record the deposit outcome', byRole: 'process_owner', description: 'Check the inventory and local deposit rules, communicate proposed deductions and process any return in the deposit scheme or payment provider.', requiredFields: ['deposit_outcome_reference'] },
    completionMessage: 'The deposit outcome has been recorded and communicated.', notes: ['Deposit deadlines and dispute rights vary by place and scheme; verify them before use.'], retentionDays: 2555,
    fields: [f.text('tenancy_reference', 'Tenancy reference'), f.date('vacated_on', 'Date vacated'), f.money('deposit_held', 'Deposit held'), f.money('proposed_deductions', 'Proposed deductions', false), f.notes('deduction_evidence', 'Condition evidence and reasons', false), f.text('scheme_reference', 'Deposit scheme reference', false), f.recorded('deposit_outcome_reference', 'Deposit outcome reference')],
  },
  {
    key: 'lease_renewal', name: 'Lease renewal enquiry', category: 'Property',
    summary: 'A renewal request checked against the current agreement and answered before expiry.',
    audience: 'For landlords and property managers handling occupier renewals.', outcome: 'The renewal decision and next contract step are recorded.',
    respondents: 'A tenant or property manager.', ownerName: 'Property management',
    approvals: [{ key: 'manager', name: 'Property manager review', byRole: 'property_manager', dueInHours: 48 }],
    task: { key: 'arrange_renewal', name: 'Arrange the agreed renewal', byRole: 'process_owner', description: 'Check the existing terms and any applicable notices, agree the proposed dates and issue documents through the usual legal route.', requiredFields: ['renewal_document_reference'] },
    completionMessage: 'The lease renewal decision and document step have been recorded.', notes: ['This is an enquiry and approval trail, not a signed lease or formal notice.'], retentionDays: 2555,
    fields: [f.text('property_reference', 'Property reference'), f.text('tenancy_reference', 'Current agreement reference'), f.date('current_end', 'Current end date'), f.date('preferred_end', 'Preferred new end date'), f.choice('request_kind', 'What is requested?', ['renew_same_terms', 'change_terms', 'end_at_expiry']), f.notes('requested_changes', 'Changes requested', false), f.recorded('renewal_document_reference', 'Renewal document reference')],
  },

  // Safeguarding
  {
    key: 'safeguarding_concern', name: 'Safeguarding concern', category: 'Safeguarding',
    summary: 'A concern about someone’s safety sent privately to the safeguarding lead for prompt action.',
    audience: 'For churches, schools and charities receiving welfare concerns.', outcome: 'A trained lead assesses the concern and records a secure case reference.',
    respondents: 'A staff member, volunteer or person raising a concern.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Safeguarding lead review', byRole: 'safeguarding_lead', dueInHours: 4 }],
    task: { key: 'record_action', name: 'Record the safeguarding action', byRole: 'safeguarding_lead', description: 'Assess immediate safety, follow the local safeguarding procedure, make any necessary referral and record the secure case reference.', requiredFields: ['safeguarding_case_reference'] },
    completionMessage: 'The safeguarding team has reviewed the concern.', notes: ['If anyone is in immediate danger, use the emergency route instead of waiting for this form.', 'Do not include the private concern in routine email notifications.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('person_at_risk', 'Person the concern is about'), f.date('noticed_on', 'When did this happen or become known?'), f.choice('concern_type', 'What kind of concern?', ['safety', 'conduct', 'neglect', 'disclosure', 'other']), f.private('concern_detail', 'What happened? Record facts and exact words where possible.', 'Safeguarding details are restricted to the safeguarding team.', true), f.yesNo('immediate_danger', 'Is someone in immediate danger now?'), f.text('others_informed', 'Who has already been told?', false), f.recorded('safeguarding_case_reference', 'Secure case reference')],
  },
  {
    key: 'safeguarding_allegation', name: 'Allegation against a worker', category: 'Safeguarding',
    summary: 'An allegation about a worker routed confidentially to an independent safeguarding decision maker.',
    audience: 'For organisations that need a separate route for concerns about staff or volunteers.', outcome: 'The allegation is triaged and referred through the organisation’s formal procedure.',
    respondents: 'The person reporting the allegation.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'designated_lead', name: 'Designated safeguarding review', byRole: 'safeguarding_lead', dueInHours: 4 }],
    task: { key: 'allegation_route', name: 'Record referral and protective steps', byRole: 'safeguarding_lead', description: 'Keep the allegation away from the person named; follow the required external and internal referral route and record a secure reference.', requiredFields: ['allegation_case_reference'] },
    completionMessage: 'The designated safeguarding lead has reviewed the report.', notes: ['Do not investigate or notify the person named through an automatic message.', 'Use the emergency route for immediate danger.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('worker_name', 'Worker named in the allegation'), f.text('worker_role', 'Their role', false), f.date('incident_date', 'When did this happen or become known?'), f.private('allegation_detail', 'Describe what was reported', 'Allegations are restricted to the designated safeguarding team.', true), f.yesNo('immediate_danger', 'Is someone in immediate danger now?'), f.text('existing_reference', 'Existing report reference', false), f.recorded('allegation_case_reference', 'Secure allegation case reference')],
  },
  {
    key: 'safeguarding_training', name: 'Safeguarding training record', category: 'Safeguarding',
    summary: 'Required training checked before someone starts a role and renewal followed up.',
    audience: 'For teams tracking safeguarding training for staff and volunteers.', outcome: 'A training record and its next review date are verified.',
    respondents: 'A staff member, volunteer or team leader.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Training verification', byRole: 'safeguarding_lead', dueInHours: 72 }],
    task: { key: 'update_training_register', name: 'Update the training register', byRole: 'safeguarding_lead', description: 'Verify the course completion with the approved source and record the register reference and renewal date.', requiredFields: ['training_register_reference'] },
    completionMessage: 'The safeguarding training record has been verified.', retentionDays: 2555,
    fields: [f.person('worker_name', 'Worker name'), f.text('worker_role', 'Role or team'), f.text('course_name', 'Training course'), f.date('completed_on', 'Date completed'), f.text('certificate_reference', 'Certificate or provider reference', false), { ...f.date('renewal_due', 'Renewal due date', false), setBy: 'operator' }, f.recorded('training_register_reference', 'Training register reference')],
  },
  {
    key: 'safeguarding_clearance', name: 'Role clearance review', category: 'Safeguarding',
    summary: 'A person’s checks, references and training reviewed before they enter a protected role.',
    audience: 'For organisations assigning people to work with children or vulnerable adults.', outcome: 'A named lead records clearance or a reason not to start.',
    respondents: 'A team leader requesting role clearance.', ownerName: 'Safeguarding team',
    approvals: [{ key: 'lead', name: 'Safeguarding clearance', byRole: 'safeguarding_lead', dueInHours: 72 }],
    task: { key: 'record_clearance', name: 'Record the role decision', byRole: 'safeguarding_lead', description: 'Check the required screening, references, training and local policy; record the decision by reference without uploading certificate copies.', requiredFields: ['clearance_decision_reference'] },
    completionMessage: 'The role clearance decision has been recorded.', notes: ['A request does not authorise the person to start. Screening requirements depend on the role and jurisdiction.'], retentionDays: 2555, sensitivityCeiling: 'restricted',
    fields: [f.person('worker_name', 'Person to be cleared'), f.text('proposed_role', 'Proposed role'), f.date('planned_start', 'Planned start date'), f.choice('contact_group', 'Who will the role involve?', ['children', 'vulnerable_adults', 'both', 'other']), f.text('screening_reference', 'Existing screening reference', false), f.text('training_reference', 'Training reference', false), f.private('review_notes', 'Anything the safeguarding lead should know?', 'Role clearance details are restricted to the safeguarding team.'), f.recorded('clearance_decision_reference', 'Clearance decision reference')],
  },

  // Sales
  {
    key: 'demo_request', name: 'Product demo request', category: 'Sales',
    summary: 'A prospect’s demo request qualified and scheduled with a clear follow-up.',
    audience: 'For sales teams arranging product demonstrations.', outcome: 'The demo is scheduled or declined with a reason.',
    respondents: 'A prospective customer.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales triage', byRole: 'sales_lead', dueInHours: 24 }],
    task: { key: 'schedule_demo', name: 'Schedule the demo', byRole: 'sales_lead', description: 'Confirm the use case, invite the right presenter and send the agreed meeting details.', requiredFields: ['demo_booking_reference'] },
    completionMessage: 'The demo request has been reviewed and the next step recorded.', retentionDays: 1825,
    fields: [f.text('organisation', 'Organisation', false), f.choice('product_area', 'What would you like to see?', ['core_product', 'integrations', 'reporting', 'pricing']), f.notes('use_case', 'What are you trying to do?'), f.choice('team_size', 'Team size', ['one_to_ten', 'eleven_to_fifty', 'fifty_plus']), f.date('preferred_date', 'Preferred date'), f.phone('contact_phone', 'Phone number', false), f.recorded('demo_booking_reference', 'Demo booking reference')],
  },
  {
    key: 'discount_approval', name: 'Discount approval', category: 'Sales',
    summary: 'A proposed discount checked against margin and authorised before a quote is sent.',
    audience: 'For sales teams with delegated pricing limits.', outcome: 'The authorised price and reason are recorded against the deal.',
    respondents: 'A sales representative.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales manager', byRole: 'sales_lead', dueInHours: 24 }, { key: 'finance', name: 'Margin check', byRole: 'finance_reviewer', dueInHours: 48 }],
    task: { key: 'record_price', name: 'Update the approved quote', byRole: 'process_owner', description: 'Use the approved price and expiry in the quoting system, then record the revised quote reference.', requiredFields: ['discounted_quote_reference'] },
    completionMessage: 'The approved discount has been recorded in the revised quote.', notes: ['Configure your actual delegation thresholds and margin rules before publishing.'], retentionDays: 1825,
    fields: [f.text('deal_reference', 'Deal reference'), f.text('customer_name', 'Customer'), f.money('list_price', 'Standard price'), f.money('proposed_price', 'Proposed price'), f.notes('discount_reason', 'Why is the discount needed?'), f.date('offer_expires', 'Offer expiry'), f.recorded('discounted_quote_reference', 'Revised quote reference')],
  },
  {
    key: 'sales_order_review', name: 'Sales order review', category: 'Sales',
    summary: 'A customer order checked against quote, capacity and delivery terms before acceptance.',
    audience: 'For sales teams handing an order to operations.', outcome: 'The order is accepted and handed off with a reference.',
    respondents: 'A sales representative or account owner.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales review', byRole: 'sales_lead', dueInHours: 24 }, { key: 'delivery', name: 'Delivery capacity', byRole: 'delivery_lead', dueInHours: 48 }],
    task: { key: 'book_order', name: 'Book and hand over the order', byRole: 'process_owner', description: 'Confirm the approved quote and terms, enter the order in the sales system and hand the delivery details to operations.', requiredFields: ['sales_order_reference'] },
    completionMessage: 'The accepted sales order and delivery handover have been recorded.', retentionDays: 1825,
    fields: [f.text('customer_name', 'Customer'), f.text('quote_reference', 'Approved quote reference'), f.notes('products_or_services', 'Products or services ordered'), f.money('order_value', 'Order value'), f.date('delivery_by', 'Requested delivery date'), f.text('purchase_order_number', 'Customer PO number', false), f.recorded('sales_order_reference', 'Sales order reference')],
  },
  {
    key: 'lead_qualification', name: 'Lead qualification', category: 'Sales',
    summary: 'An inbound lead assessed and routed to a named owner for a next conversation.',
    audience: 'For sales teams receiving enquiries from several channels.', outcome: 'The lead is qualified or declined with an owner and next action.',
    respondents: 'A prospective customer or sales team member.', ownerName: 'Sales',
    approvals: [{ key: 'sales', name: 'Sales triage', byRole: 'sales_lead', dueInHours: 24 }],
    task: { key: 'assign_lead', name: 'Assign owner and next action', byRole: 'process_owner', description: 'Check fit, contact preference and consent, assign an account owner and record the next action in the CRM.', requiredFields: ['crm_lead_reference'] },
    completionMessage: 'Your enquiry has been reviewed and the next action recorded.', retentionDays: 1825,
    fields: [f.text('organisation', 'Organisation', false), f.choice('interest_area', 'Area of interest', ['product', 'service', 'partnership', 'other']), f.notes('business_need', 'What are you looking for?'), f.choice('timeline', 'When are you looking to start?', ['now', 'this_quarter', 'later', 'exploring']), f.choice('contact_preference', 'How should we contact you?', ['email', 'phone']), f.yesNo('contact_permission', 'May the sales team contact you about this enquiry?'), f.recorded('crm_lead_reference', 'CRM lead reference')],
  },
];
